### ISSUE TITLE
Works on remote server, but not on local server.

### ISSUE THREAD

**Issue by theasder** [eleith/emailjs#103]
Module works great on remote server, but on localhost it gives following error: "Error Sending: Email failed to send. Error: authorization.failed". I have no idea why, everything on local server works just fine.

**Comment by watadarkstar** [comment]
For me the issue was that Google no longer supports username and password only. It now requires 2FA app passwords. See here:
https://support.google.com/accounts/answer/6010255?sjid=16626078911211144448-NA
