### ISSUE TITLE
Gmail smtp not working 

### ISSUE THREAD

**Issue by abhiram57** [eleith/emailjs#104]
Hie,

I have been using emailjs quite for some time and since last evening i was unable to send emails.

The following are the error codes I am getting all different times.
1st time:
error :  code 7
error :  smtp undefined

2nd time:

error :  code 3
error :  previous { [Error: bad response on command 'AUTH'] code: 2, smtp: '250 CHUNKING\n' }
error :  smtp undefined

My code is:
var ES = require('./email-settings');
var EM = {};
module.exports = EM;

EM.server = require("emailjs/email").server.connect({

```
host        : ES.host,
user        : ES.user,
password    : ES.password,
ssl         : true
```

});

EM.dispatchResetPasswordLink = function (account, callback) {
    EM.server.send({
        from: ES.sender,
        to: account.email,
        subject: 'Password Reset',
        text: 'something went wrong... :(',
        attachment: EM.composeEmail(account)
    }, callback);
};

EM.dispatchWelcomeMessage = function (account, callback) {
    EM.server.send({
        from: ES.sender,
        to: account.email,
        subject: 'Welcome to Brainwave',
        text: 'Welcome to Brainwave',
        attachment: EM.composeWelcome(account)
    }, callback);
};

I am using normal authentication and no two step authentication is being used .

What exactly is the issue can anyone fix this?

**Comment by var786** [comment]
Not working in the latest nodemailer/emailjs. :(

**Comment by SkateFreak** [comment]
suddenly for no reason i started getting this error too.

``` "emailjs": "^1.0.8",```

**Comment by WilliamDrive** [comment]
I have the same issue for same version: 1.0.8.  any idea?

**Comment by yinfxs** [comment]
1.0.9, me too

**Comment by mef** [comment]
@SkateFreak @WilliamDrive @yinfxs This issue has been solved and is closed. 

If the problem is back and there is a regression, you may want to open a new issue.

**Comment by eleith** [comment]
with 1.0.9 i am able to get a non enterprise gmail account to send email with this library using the below code

```javascript
var email   = require("./email");
var server  = email.server.connect({
   user:      "my-gmail-address@gmail.com",
   password:  "app-password",
   host:      "smtp.gmail.com",
   ssl:       true
});
```

i generated the app password (you need to do this if you have 2 factor turned on) at: https://security.google.com/settings/security/apppasswords

**Comment by tigerss** [comment]
I just had the same problem using winston-mail and this worked for me

1) Login to your gmail account.

2) Go to https://www.google.com/settings/security/lesssecureapps and Turn On this feature.

3) Go to https://accounts.google.com/DisplayUnlockCaptcha and click Continue.

source https://serverfault.com/a/745666

**Comment by victorazevedo** [comment]
You have to allow in the gmail the access to the server to login in with smtp

**Comment by vijay-pratap** [comment]
### Here is the code for email send provided by the mailjs.  I have used this and it **works for me**.

`var email 	= require('../../../node_modules/emailjs/email');  **// ADD CORRECT PATH OF emailjs/email**
var server 	= email.server.connect({
   user:    "yourmail@gmail.com", 
   password:"your-app-password-16-digit", 
   host:    "smtp.gmail.com", 
   ssl:     true
});
 
// send the message and get a callback with an error or details of the message that was sent
server.send({
   text:    "i hope this works", 
   from:    "<youremail@gmail.com>", 
   to:      "<otheremail@gmail.com>",
   subject: "Your Message"
}, function(err, message) { console.log(err || message); });`

Get your 16-Digit Password from here : 

1. Go to your Google Account.
2. On the left navigation panel, click Security.
3. On the Signing in to Google panel, click App passwords. 
**Note: If you can't get to the page, 2-Step Verification is:
Not set up for your account**
4. Set up for security keys only
5. At the bottom, click Select app and choose the app you’re using.
6. Click Select device and choose the device you’re using.
7. Click Generate.
**Follow the instructions to enter the App password (the 16 character code in the yellow bar) on your device.**
8. Click Done.

[https://myaccount.google.com/security](url)

**Comment by theambidextrous** [comment]
same issue here... one minute sending well, next minute fails
