### ISSUE TITLE
npm install emailjs worked but all attempts at require fail

### ISSUE THREAD

**Issue by tombates** [eleith/emailjs#112]
I'm fairly new to node et. al. and I've installed several packages and used them happily but I am having a real issue with getting emailjs to even get loaded. After the "install npm emailjs", which worked without errors, I do indeed see the whole emailjs tree inside node_modules off the root of my project just like any other package install.

I have tried many variations now on the require statement in the router where I want to use emailjs but they all fail at npm start time with error statements about a failure to find required middleware the details of which according to exactly what require I try.  Apparently I do not understand what require("./path/to/emailjs/email") should become in my case even. I realize you don't have all my code here but I'd thought I'd first see if there's just something simple I'm just missing regarding the darn require statement:

For emailjs none of the following have worked:

//var email = require('emailjs/email');
//var email = require('node_modules/emailjs/email');
//var email = require('./node_modules/emailjs/email');
//var email = require('./emailjs/email');
//var email = require('email');
//var email = require('emailjs');

Apparently I do not understand what require("./path/to/emailjs/email") should become in my case even though I don't have to do anything for any other package other than require('packagename') to get it to go. I realize you don't have all my code here but I'd thought I'd first see if there's just something simple I'm just missing regarding the darn require statement:

I apologize if this is not appropriate as an issue here but I've found no help from google and I'm about to give up on emailjs and I really don't want to. Thanks.

**Comment by pushkarmoi** [comment]
Hi i am having the same issue. What moule.exports line? and where??

**Comment by eleith** [comment]
after `npm install emailjs` you just need to `require('emailjs')`

**Comment by kyabroudi** [comment]
same issue here !!

**Comment by eleith** [comment]
if you use npm to install emailjs all you need to do is `const emailjs = require('emailjs')` if you install from github, you'll need to run `npm install` in the emailjs directory before you can use this library
