### ISSUE TITLE
Do not call multiple times callback

### ISSUE THREAD

**Issue by ghost** [eleith/emailjs#113]
When trying to send an email with a wrong configuration, for example, with a wrong SMTP server (`getaddrinfo ENOTFOUND`). I will submit a PR trying to fix the issue.

**Comment by rafalneves** [comment]
This still happens due to:

smtp.js(64)
self.sock.once('response', response);
self.sock.once('error', response);

If there is a response and an error we have two callbacks, the two events will be fired...

**Comment by eleith** [comment]
pushed to npm, try again. an open pull request was closed when @rafalneves realized that the latest master never made it to npm
