### ISSUE TITLE
451 - bare linefeed issue

### ISSUE THREAD

**Issue by StewartNoyce** [eleith/emailjs#118]
I am sending email through an account on one of my domains hosted by network solutions. After connection is established and message content is sent, the host responds with "451 See http://pobox.com/~djb/docs/smtplf.html."  The referenced page says the mailer sent an email message with a bare lf, meaning no cr included.  Any suggestions on how to get this to work?

**Comment by eleith** [comment]
does it always respond that way to any message or just that particular message? a code snippet would be helpful if you can provide a small test case that fails on you.

emailjs should not send bar LFs but CRLF together -> https://github.com/eleith/emailjs/search?utf8=%E2%9C%93&q=crlf

but perhaps there is a bug somewhere.

**Comment by StewartNoyce** [comment]
Thanks for the pointer to the CRLF variable.  Clearly, the intent is there.  

I found the problem when using Drywall, which includes emailjs as it's mailer.   It uses a [sendmail module](https://github.com/jedireza/drywall/blob/master/util/sendmail/index.js) to send a message through emailjs.   

Here's another clue though.  After I posted the issue, I tried an email account on Earthlink.  It worked fine.  So, this may simply be an incompatibility with the servers at Network Solutions.  That would be a shame because I want to use the email I have hosted there.

**Comment by eleith** [comment]
so all messages encounter this issue? no matter the content/title?

**Comment by StewartNoyce** [comment]
I tried [/login/forgot](https://github.com/jedireza/drywall/blob/master/views/login/forgot/index.js) and [/contact](https://github.com/jedireza/drywall/blob/master/views/contact/index.js) in Drywall.  Both had the same issue.

**Comment by eleith** [comment]
still can't reproduce, if you can find a code snippet that i can reproduce, i'll be happy to look into it and fix it

**Comment by StewartNoyce** [comment]
I isolated the problem.  The /contact code in Drywall uses jade to render text and html versions of a form with input data.  The html works fine by itself.  The jade-rendered text prompts the 451 error.

**Comment by StewartNoyce** [comment]
Leith,

I just added a note to this issue.  Ironically, I had just started 
working on my project again the day you closed it.

It looks like a corner case with jade rendering of text rather than 
html.  A single line jade template worked fine, but two lines broke it.

See attached files.  Run the js file with node (with emailjs 1.0.1 and 
jade 1.11 node_modules) and use the email-text.jade file as a template.

I found the problem when using the smtp server at network solutions 
where I host my domains.  Do you have an account there?

Do with it what you will.  I need to work around the problem, and 
String(jadetext) didn't solve it.  I may just write a little utility for 
string building.

Thanks,
Stewart


On 3/6/15 10:01 AM, eleith wrote:
>
> so all messages encounter this issue? no matter the content/title?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/eleith/emailjs/issues/118#issuecomment-77604996>.
>

-- 

Stewart Noyce
TruNorth Consulting <www.trunorth.com>
510.917.1927

| Contact Form
| with a second line
