### ISSUE TITLE
Undocumented return types

### ISSUE THREAD

**Issue by r3wt** [eleith/emailjs#123]
What is the return type for `error` in `send( callback(err,res) )`

i need to return `1` for failure, `0` for success. Am i correct in assuming i can just convert to bool -> convert to int?

```
var result;
server.send({
   text:    template, 
   from:    config.from, 
   to:      data.recipient,
   subject: data.subject
}, function(error, message) { 
	result = {'error': ~~( !!error ),'message'=>0};
}); 
res.writeHead(200,'OK',{'Content-Type': 'application/json'});
res.write(JSON.stringify(result)).end();
```

**Comment by eleith** [comment]
error is an error object. if error is not null, then you have an error and you can inspect the object to see the message of the error. 

if the error is null, you can ignore it and assume the email was sent.
