### ISSUE TITLE
Supporting file upload

### ISSUE THREAD

**Issue by ar7casper** [eleith/emailjs#125]
I'm using HTML5 API to send the files to the server which then takes this file and sends it to a specific email. 
That's the code i'm using - 
    text:    "event " + daEvent + " likes: " + likes + " figure: " + figure, 
        attachment: {
   	data: file
        },
        from:    email, 
        to:      "Nir <dsome.email@email.com>",
        cc:      "",
        subject: "Styling Online Incoming"
       }  , function(err, message) { console.log(typeof message, err || message); 

Any idea why it doesn't work?

**Comment by eleith** [comment]
what are you passing in as "file" ?

**Comment by ar7casper** [comment]
An image. Jpeg.

**Comment by eleith** [comment]
what is the error you get when running the code you pasted?

**Comment by sesamechicken** [comment]
@ar7casper Why not use the path property?

**Comment by ar7casper** [comment]
What do you mean by the path property?

Alex

**Comment by sesamechicken** [comment]
Well if you're uploading the file, then you have its path, why not construct the email to use the path property of the attachment object? https://github.com/eleith/emailjs#example-usage---html-emails-and-attachments

The example works exactly as you'd expect, and we still don't know the error you're receiving.

**Comment by ar7casper** [comment]
Cool, thanks, I'll have a look in the next couple of days.

**Comment by ar7casper** [comment]
Hi,

This is the error I'm getting -
{
    [Error: authorization.failed]
    code: 3,
        previous: {
            [Error: bad response on command 'ams3OEVWZXY=']
            code: 2,
                smtp: '534-5.7.14 <
https://accounts.google.com/ContinueSignIn?sarp=1&scc=1&plt=AKgnsbvZn\n534-5.7.14
qSxvB8OZWyqcX41br1Q6cnBJQGxoT_XX4oo63eyxqegTzQSdCwunlRI1ZAPOyg7sLWvpmH\r\n534-5.7.14
TgdSF3_TW9fPbgSVSMo1urdGwUBSl1DYxHjY0LuUxabDFWE6zs5t9eYTF9dWp6FN8t-ayM\r\n534-5.7.14
c0MPAm-6AOYhIsdTOzLF4EWHcQhd3IENO6v6QjL2WiSUONjDYV137Fe4_NvqQG_GhMvRLf\r\n534-5.7.14
GVHXHf4GSOclTivqMNCzO0C5eWgQ> Please log in via your web browser
and\r\n534-5.7.14 then try again.\r\n534-5.7.14 Learn more at\r\n534 5.7.14
https://support.google.com/mail/answer/78754 em17sm580990wid.11 - gsmtp\r\n'
        },
        smtp: undefined
}

Alex

**Comment by ar7casper** [comment]
Please note that when I'm posting to localhost, all works great, when it's
in production, this is the error i get.

Thanks!

Alex

**Comment by jacoborus** [comment]
Try this: https://www.google.com/settings/security/lesssecureapps

**Comment by ar7casper** [comment]
Been there, done that :)
Doesn't help

**Comment by sesamechicken** [comment]
For gmail, the port should be 465. Does that get you anywhere? Google might
throw a warning to you about an unauthorized app trying to send email using
your account. You're going to have to allow it (google will provide the url
to do this in the warning).

**Comment by ar7casper** [comment]
Yep, done all that, nothing seems to help.

**Comment by eleith** [comment]
sorry. i can not reproduce. for testing i tried out a gmail account using a one time app password and it works.

**Comment by jacoborus** [comment]
@ar7casper are you sure you enable less secure apps with gmail account you are trying to send emails?

**Comment by eleith** [comment]
still can not reproduce
