### ISSUE TITLE
 No form of authorisation supported Error

### ISSUE THREAD

**Issue by sauravkp** [eleith/emailjs#126]
Hi, 
I am getting the below error while trying to send mail. I am using a zoho smtp server i.e. smtp.zoho.com .
"Error Sending: Email failed to send. Error: no form of authorisation supported".
I checked all the issues opened for this i.e. #81, #104. According to #104, the issue was resolved from  version 3.10.  This time I am using the latest version 3.16 but the issue seemed to be popped up again. 
From my investigation I got to know that error is coming from this part of smtp.js.

        else if (method == AUTH_METHODS.LOGIN) self.command("AUTH " + AUTH_METHODS.LOGIN, attempt_user, [334]);

        else if (method == AUTH_METHODS.PLAIN) self.command("AUTH " + AUTH_METHODS.PLAIN + " " + encode_plain(login.user(), login.password()), response, [235, 503]);

        else if (method == AUTH_METHODS.XOAUTH2) self.command("AUTH " + AUTH_METHODS.XOAUTH2 + " " + encode_xoauth2(login.user(), login.password()), response, [235, 503]);

        else if (!method) caller(callback, SMTPError('no form of authorization supported', SMTPError.AUTHNOTSUPPORTED, null, data)); "

I tried the solution provided in #81 but it is not working anymore. 
Anything I am doing wrong?

**Comment by eleith** [comment]
what forms of authorization are supported by the server?
