### ISSUE TITLE
header parse bug

### ISSUE THREAD

**Issue by semjada** [eleith/emailjs#129]
smtp/message.js line 85

else if(/cc|bcc|to|from/i.test(header))
should read
else if(/^(cc|bcc|to|from)$/i.test(header))

i found myself unable to add "in-reply-to" headers properly (<, > in the Message-ID being removed) because of this bug.
cheers

**Comment by eleith** [comment]
thanks. feel free to make a PR next time.

**Comment by eleith** [comment]
fix is on master

**Comment by semjada** [comment]
cheers! will do.
