### ISSUE TITLE
callback on server connect

### ISSUE THREAD

**Issue by asensoy** [eleith/emailjs#131]
hi, i'm missing a callback function on server connect similar to the npm module smtp-connection. i'm only able to increase the timeout, but it's not bulletproof safe.

**Comment by eleith** [comment]
can you clarify? 

have you tried also listening to errors to see what error is being thrown on the request to connect?

**Comment by asensoy** [comment]
hi, i would like to get a callback if the server connection is established before i send the mail, after i send the mail and get an error it's too late.

**Comment by PatrickMurphy** [comment]
Do you mean the callback in this function that is supplied as an argument?
https://github.com/andris9/smtp-connection/blob/master/src/smtp-connection.js#L140

Or these events that are bound to it when the connection is established?
https://github.com/andris9/smtp-connection/blob/master/src/smtp-connection.js#L301

If you make a clear request I would be happy to help!
