### ISSUE TITLE
How to change the from field in the content

### ISSUE THREAD

**Issue by 14307130040** [eleith/emailjs#133]
The from field of the content of the mail could be different from that in the smtp protocol, which can be used to make the recipients reply to the correct sender when the mail is transmitted by another. Thus they should be different and a way to assign the pure content should be provided.

**Comment by eleith** [comment]
this is what the header "reply-to" is used for. that way you can separate out the from field from what happens when the user hits reply.

**Comment by eleith** [comment]
here is the documentation on how to send headers

https://github.com/eleith/emailjs#message

just ensure to send an email within the "reply-to" header
