### ISSUE TITLE
Doesn't send via TLS / STARTTLS

### ISSUE THREAD

**Issue by Ulawun** [eleith/emailjs#134]
Hello eleith,

Great work, thanks.
I'm sorry to say,
that it doesn't work for me.
I get this Error:
{ [Error: bad response on command 'helo'] code: 2, smtp: '500 TLS Negotiation Failed\n' }
The settings work fine with Thunderbird: STARTTLS, Port: 587
Yes, I tries ssl instead of tls.
Any Ideas ?
Thanks a lot.

*** code ***

var email = require( "emailjs" );

var server = email.server.connect(
{	user: ###xy.com",
	password: "###",
	host: "###xy.com",
	tls: true, // STARTTLS, Port: 587
} );

var message =
{	text:    "i hope this works",
	from:    "U <###xy.com>",
	to:      "someone <###.net>, another <###.net>",
	subject: "testing emailjs",
};

server.send( message, function( err, message )
{	console.log( err || message );
} );

**Comment by Ulawun** [comment]
Hello again,

My problem is still unfixed.
I tried several email accounts without any success.
What do I have to insert for 'password' ?
Is it my plain password or any kind of crypt or hash ?
Did anybody successfully send a mail via Google account ?
Here my Google test:

*** server.connect ***

var server = email.server.connect(
{	user: '###@gmail.com',
	password: '###',
	host: 'smtp.gmail.com',
	ssl: true,
} );

*** error ***

{ [Error: authorization.failed]
  code: 3,
  previous:
   { [Error: bad response on command 'aGd6RmRoejVqc3loSGQza2pKYnM3']
     code: 2,
     smtp: '534-5.7.14 <https://accounts.google.com/ContinueSignIn?sarp=1&scc=1&
plt=AKgnsbtL-\n534-5.7.14 9nkh-56U2oCEcS6yZNG6H7bvSQmCO_6bL0BZkGvNdHXES0HkPSqDgl
7zATE8KT4QTvAmW_\r\n534-5.7.14 XceMB3Sv7BjCRkJ4nvaPocgQPQKv4K7c9MhcmvH-BKGhWHQZu
Y5EaQ-hAeU-6B35MY0RaL\r\n534-5.7.14 P58z8JShGd1c7hwT4wpdGuXL1G_bdor5P4BVzmad70d8
RWgmVEmK0_ROk4g9kByme-GMuy\r\n534-5.7.14 L2AktQfAJVBagYfhoQy4-HqRXPk0> Please lo
g in via your web browser and\r\n534-5.7.14 then try again.\r\n534-5.7.14  Learn
 more at\r\n534 5.7.14  https://support.google.com/mail/answer/78754 s2sm3573684
4wmd.13 - gsmtp\r\n' },
  smtp: undefined }

**Comment by eleith** [comment]
if you are using gmail and you have two factor authentication setup, you will not be able to use emailjs with your normal password.

you will need to create an application specific password as noted in the readme for emailjs

https://github.com/eleith/emailjs#requires
