### ISSUE TITLE
emailjs throwing a getaddrinfo ENOTFOUND smtp.gmail.com error 

### ISSUE THREAD

**Issue by saicharanp** [eleith/emailjs#136]
`var email = require('emailjs/email');`

```
var server = email.server.connect({
        user:    "username@gmail.com",
        password:"password22",
        host:    "smtp.gmail.com ",
        ssl:     true,
        port : 465
    });
    server.send({
        text:    "i hope this works",
        from:    "user <username@gmail.com>",
        to:      "user <username@gmail.com>",
        cc:      "",
        subject: "testing emailjs"
    }, function(err, message) { console.log(err || message); });
```

I am getting the following error in console

```
{ [Error: connection encountered an error]
  code: 5,
  previous:
   { [Error: getaddrinfo ENOTFOUND smtp.gmail.com ]
     code: 'ENOTFOUND',
     errno: 'ENOTFOUND',
     syscall: 'getaddrinfo',
     hostname: 'smtp.gmail.com ' },
  smtp: undefined }
```

**Comment by eleith** [comment]
i can not replicate.

this error "getaddrinfo ENOTFOUND smtp.gmail.com" likely means your DNS is not resolving smtp.gmail.com for some reason.

try on another machine to verify that this is indeed the case

**Comment by ashutoshdev** [comment]
Hello ,
I am also getting error 
Server up: http://localhost:3300
{ [Error: getaddrinfo ENOTFOUND 1234 1234:465]
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: '1234',
  host: '1234',
  port: 465 }

**Comment by XiSmartElf** [comment]
same here

**Comment by IveSix** [comment]
same here

**Comment by wujunchuan** [comment]
same here

**Comment by gogas** [comment]
same here

**Comment by wujunchuan** [comment]
After that I solved this problem.
You can make sure your DNS can resolving the Email server address.

just have a try 

```bash
nslookup smtp.gmail.com
```

**Comment by siteantipas** [comment]
I have tried the above code 
`nslookup smtp.gmail.com`
in command prompt, my machine can resolve to it but it still giving that error.

**Comment by gelinger777** [comment]
just for those who could be having this error. Please check that you did not copy by mistake a white-space before or after the value of the SMTP server host. In that case DNS resolver fails.

**Comment by zackschuster** [comment]
@eleith do you think we should trim the host etc. strings?

**Comment by gelinger777** [comment]
@zackschuster  yes, a basic trim whitespaces before after and remove unallowed characters for domain name  would be good

**Comment by eleith** [comment]
@zackschuster / @gelinger777 good point. 

i think it depends on what is the best way to define the intent of the user input in this API. 

there are two approaches

1) treat input as _suggestive_ and the library _fixes_ input when there is some level of confidence

2) treat input as _determinant_ and provide better error messaging like _did you mean X instead of Y_ ?

if we isolate this treatment to the host, trimming feels appropriate / high confidence enough without having to wade deeper into what to do with all the other input handling =]

**Comment by zackschuster** [comment]
@eleith i agree, the first change should be limited to host & more changes can be explored later if desired or necessary. off the top of my head i think we would want to evaluate the existential checks next (e.g. `!str`  or `str1 || str2`).

**Comment by zackschuster** [comment]
@eleith should we move forward with host trimming?

**Comment by eleith** [comment]
sounds good!

**Comment by zackschuster** [comment]
@eleith done in b3fa0babf80b2b27c727e1dc9b8901f8f8ca206e. i chose to do it the more verbose way to leave user configuration intact, in case changing that would confuse anyone :)
