### ISSUE TITLE
False timeout error

### ISSUE THREAD

**Issue by DamienP33** [eleith/emailjs#142]
I'm using OVH SMTP and when I send an email with `send` method, I always get the following error :
` { [Error: timedout while connecting to smtp server] code: 4, smtp: undefined }` whereas email is sent.
When I enable the debug, the return of SMTP is OK : `250 ok 1452602503 qp 28035`

**Comment by eleith** [comment]
when you enable debug, it is possible that the debug statements eat up some time thus allowing your email to send.

instead, i recommend you just increase the timeout to see what effect that happens. the default is 5000 ms.

**Comment by DamienP33** [comment]
I have already fix the timeout to 10000ms but the problem persist...

**Comment by pekpon** [comment]
hey same problem here! any solution?

**Comment by DamienP33** [comment]
No, I switched to NodeMailler ...

**Comment by pekpon** [comment]
Ops, thanks!

**Comment by eleith** [comment]
can someone paste a snippet of how i can reproduce this? i'ld like to fix it if it can be reproduced by others.

**Comment by DamienP33** [comment]
that's my old service :
 ```
var email   = require("emailjs");
 var mailer  = email.server.connect({
     user: mailCfg.mailer.address,
     password: mailCfg.mailer.password,
     host: mailCfg.mailer.host,
     ssl: mailCfg.mailer.ssl
 });
 
 module.exports = {
     sendEmail: function(email) {
         var deferred = Q.defer();
 

         mailer.send(
             {
                 from:    mailCfg.address.noreply,
                 to:      email.receiver,
                 subject: email.subject,
                 text:    email.message,
                 bcc:     'bar@foo.com',
                 attachment: [
                     {data: email.message, alternative:true}
                 ]
             },
             function(error, message) {
                 if (error) {
                     return deferred.reject(error)
                 }
                 return deferred.resolve(message);
             })
         ;
         return deferred.promise;
     }
};
```

**Comment by eleith** [comment]
thanks. turns out if there is a timeout, you need to call end on the stream manually.

**Comment by Radivarig** [comment]
@eleith thanks! Putting 10 sec instead of default 5 worked.
