### ISSUE TITLE
moment ReDoS vulnerability in < 2.11.2

### ISSUE THREAD

**Issue by akoskm** [eleith/emailjs#144]
```
┌───────────────┬─────────────────────────────────────────────────────────────────┐
│               │ Regular Expression Denial of Service                            │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Name          │ moment                                                          │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Installed     │ 1.7.0                                                           │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Vulnerable    │ <2.11.2                                                         │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Patched       │ >=2.11.2                                                        │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Path          │ 10log-base@1.0.0 > emailjs@1.0.2 > moment@1.7.0                 │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ More Info     │ https://nodesecurity.io/advisories/55                           │
└───────────────┴─────────────────────────────────────────────────────────────────┘
```

**Comment by vivinRajagopalan** [comment]
Hi ,
I am getting this error when i am trying to send an Email.
{ [Error: connection encountered an error]
  code: 5,
  previous:
   { [Error: getaddrinfo EAI_FAIL smtp.connectingvivin@gmail.com:465]
     code: 'EAI_FAIL',
     errno: 'EAI_FAIL',
     syscall: 'getaddrinfo',
     hostname: 'smtp.connectingvivin@gmail.com',
     host: 'smtp.connectingvivin@gmail.com',
     port: 465 },
  smtp: undefined }

**Comment by akoskm** [comment]
Do you think it's related to this particular merge request? What version you're using?

**Comment by vivinRajagopalan** [comment]
hi,
I guess it is 1.0.2

**Comment by eleith** [comment]
i merged it, but i have not pushed out a new npm module yet

**Comment by eleith** [comment]
@vivinRajagopalan  the hostname and host look wrong. they should be fqdn hosts and not email addresses.

**Comment by vivinRajagopalan** [comment]
do you please have some example ?

**Comment by eleith** [comment]
why don't you past in the code you were using and maybe we can suggest what should be used instead

**Comment by vivinRajagopalan** [comment]
Please find below the code i tried


var server  = email.server.connect({
   user:    "user@gmail.com", 
   password:"xxxx", 
   host:    "smtp.user@gmail.com", 
   ssl:     true
});

// send the message and get a callback with an error or details of the message that was sent
server.send({
   text:    "i hope this works", 
   from:    "user <user@gmail.com>", 
   to:      "user <user@xyz.com>",
   cc:      "",
   subject: "testing emailjs"
}, function(err, message) { console.log(err || message); });

**Comment by eleith** [comment]
i believe your host needs to be `smtp.google.com` not `smtp.user@gmail.com`

**Comment by vivinRajagopalan** [comment]
Hi Thanks . I tried the host as smtp.gmail.com and it worked but now i am getting a different error

{ [Error: authorization.failed]
  code: 3,
  previous:
   { [Error: bad response on command 'Z2lyaUAxMjM=']
     code: 2,
     smtp: '534-5.7.14 <https://accounts.google.com/ContinueSignIn?sarp=1&scc=1&plt=AKgnsbuw8\n534-5.7.14 abjMuaYl9MktTVtkiCUIshBrqbBMNo4VZtnqGL7yQLfMK-7gDBRZEi3oLvoi7k0eXQwB1q\r\n534-5.7.14 M0B307fnE
k21nGwUsIJqiDalHTL1J1ZabQ0ps1NRZdIH8UO6I3R0rvtYSTIUsHaey2c40B\r\n534-5.7.14 IbK-b9hbjuYr61pUV246sxEL2rlrXeCyrGrr8izXQMngKCsRVD1pX7QzsOc673Fns-Hkdw\r\n534-5.7.14 -NNftH4GFCGHuU2C_Kz4pzlYr_ck> Please lo
g in via your web browser and\r\n534-5.7.14 then try again.\r\n534-5.7.14  Learn more at\r\n534 5.7.14  https://support.google.com/mail/answer/78754 n8sm26631059pfj.46 - gsmtp\r\n' },
  smtp: undefined }

**Comment by eleith** [comment]
sounds like you have google 2 authenticator on your account and you need to get an application specific password for apps that you want to sign into your google account.

that is linked to here: https://support.google.com/mail/answer/14257?rd=1

**Comment by vivinRajagopalan** [comment]
Thanks
