### ISSUE TITLE
email.js missing on npm v 1.0.3

### ISSUE THREAD

**Issue by OriginalEXE** [eleith/emailjs#148]
Hello,

not sure if it's just me, but when I do a npm install of 1.0.3, for some reason the package does not include email.js file causing the error of emailjs package not being located by require.

I tested multiple times and on two different machines, so it might be worth looking into, but maybe it's just me screwing something up.

When I install 1.0.2, I don't get such error.

I'm running latest version of node and npm.

**Comment by eleith** [comment]
i can confirm. odd.

**Comment by eleith** [comment]
updated to 1.0.4 and it is fixed.
