### ISSUE TITLE
Getting error when ever i try to use nodemailer

### ISSUE THREAD

**Issue by ashutoshdev** [eleith/emailjs#149]
Server up: http://localhost:3300
{ [Error: getaddrinfo ENOTFOUND 1234 1234:465]
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: '1234',
  host: '1234',
  port: 465 }

**Comment by eleith** [comment]
did you mean to post this on the nodemailer project?

this error happens when the server you are trying to hit is unreachable. so either the server at localhost:3300 is not running or it is not reachable from the computer you are trying to send email from.
