### ISSUE TITLE
attachment base64

### ISSUE THREAD

**Issue by balkarov** [eleith/emailjs#150]
Hello!

I have base64 string.
When i send html body with 

```
attachment:
[
{data:"<html> <body> <img src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAFA3PEY8..."> </body> </html>", alternative:true}
]

```

But gmail web does not display a picture

I want to attach a file from base64. How can I do it?
I tried so:

```
attachment:
[
{data:"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAFA3PEY8...", encoded:true, name:"file.jpeg",type:"image/jpeg"},
]
```
But the image comes damaged

**Comment by eleith** [comment]
check out this test: https://github.com/eleith/emailjs/blob/master/test/message.js#L186

you'll need to send a header with the content-id and use that id to embed the image in your html email.

**Comment by balkarov** [comment]
I made
```
attachment:
			{
				data: '<html><body><div>this is how smtp works: <br> <br> <img src="cid:smtp-diagram@local"> </div> </body> </html>',
				alternative:   true,
				related:
						[
							{
								data:   base64string,
								encoded: true,
								type:    "image/jpeg",
								name:    "smtp-diagram.jpeg",
								headers: {"Content-ID":"<smtp-diagram@local>"}
							}
						]
			}
```

But image coms damaged

**Comment by eleith** [comment]
emailjs expects that if you use the `data` field when using attachments, that this field is not encoded. so either attach it using `path` or decode your base64 and pass it in as `data`
