### ISSUE TITLE
Moment Locale

### ISSUE THREAD

**Issue by muxe** [eleith/emailjs#151]
Hi,

I think there's a potential bug when you set your momentjs locale to something different than "en" somewhere in your node project because then the Date header field in message.js:54 gets set to (e.g.)

> Do., 03 Mrz. 2016 14:15:21 +0100

which email servers don't seem to parse.

Otherwise a great project. Thanks!

**Comment by eleith** [comment]
fascinating. what are your suggestions to resolve this ticket?

**Comment by muxe** [comment]
currently I store the current locale, set the locale to en, do the mail stuff and reset the it to the stored one. I don't know how good of a workaround this is

**Comment by jholster** [comment]
I created a pull request which resolves this issue: #153
