### ISSUE TITLE
Write a complete and better API

### ISSUE THREAD

**Issue by Xstoudi** [eleith/emailjs#154]
Hey !
I just wanted to create a TypeScript definition file for EmailJS, but to do this I need a better API with every functions and types detailled. 
Thanks :)

**Comment by eleith** [comment]
i haven't used typescript before. can you provide an example of what you would need?

**Comment by Xstoudi** [comment]
The NodeJS doc is a good example https://nodejs.org/api/
But I think it's a little "too much".
I just need a list of classes, their functions, methods, properties, etc... that are usable with EmailJS.

**Comment by eleith** [comment]
i believe the Readme on this project has all the information you need then right?
