### ISSUE TITLE
ReferenceErrors

### ISSUE THREAD

**Issue by franalt** [eleith/emailjs#158]
I'm pretty new at this and Im getting the following errors: 

ReferenceError: Can't find variable: require
ReferenceError: Can't find variable: exports

Anybody has a complete sample project of emailjs working or can point me in the right direction?

Thanks in advance!

**Comment by eleith** [comment]
can you paste in your entire example code to better help others debug with you?

**Comment by franalt** [comment]
I just filled in what was in the guide.

Inside my project folder I have **index.html** and a folder called **assets**. Inside assets I have a folder called **emailjs** where I placed all the emailjs files. So it reads **project/assets/emailjs/...**

I have linked **emailjs.js** at **index.html** (Where I get the export ReferenceError) and then when I run **functions.js** I get the require ReferenceError.

This is my **functions.js** code.

`  

            var email = require('assets/email.js');
			var server = email.server.connect({
			  user: '*********',
			  password: '*********',
			  host: '*******',
			  ssl: true
			});

			server.send({
			  text: 'Test',
			  from: 'Notificaciones Estudio Lanusse',
			  to: '**********',
			  cc: '**********',
			  subject: 'Testing Email Server'
			}, function (err, message) {
			  console.log(err || message);
			});`

Im sure Im making a ton of mistakes...

**Comment by eleith** [comment]
the proper way to install emailjs is to run the install using npm, such that the dependencies will be installed as well.

`npm install emailjs`

also, please note, emailjs is a node module and will only run on the server, it will not run in the browser because it relies on connecting to sockets, opening up files, etc etc
