### ISSUE TITLE
Embedding images

### ISSUE THREAD

**Issue by pvorb** [eleith/emailjs#16]
emailjs is a great and easy to use! Exactly what I need.

But now I have a Problem:

I wanted to embed some images into an HTML-email. You can do this by defining a `src` with a content-id like this:

``` html
<img src="cid:uniqueidentifier"` width="100" height ="50">
```

Additionaly you have to add this identifier in the header of the image.

```
------=_NextPart_000_000E_01C5BEB4.946C1870 
Content-Type: image/png; 
   name="header.png" 
Content-Transfer-Encoding: base64 
Content-ID: <uniqueidentifier> 

/9j/4AAQSkZJRgABAgAAZABkAAD/7AARRHVja3kAAQAEAAAAQwAA/+4AJkFkb2JlAGTAAAAAAQMA 
FQQDBgoNAAAVAAAAIvoAADfBAABPTP/bAIQABQMDAwMDBQMDBQcEBAQHCAYFBQYICQcHCAcHCQsJ 
CgoKCgkLCwwMDAwMCw4ODg4ODhQUFBQUFhYWFhYWFhYWFgEFBQUJCAkRCwsRFA8ODxQWFhYWFhYW...
```

I can't find a way to realize this with emailjs. Do you plan to implement such functionality?

**Comment by legaultpierre** [comment]
Hi,
Just a small message for these like me that have searched for a long time why with this code the image is not embed:
If your HTML code is 
```
<img src="cid:my-image"` width="100" height ="50">
```
Then you need to write 
```
headers:{"Content-ID":"<my-image>"}
```
instead of
```
headers:{"Content-ID":"my-image"}
```

I finally found looking in the tests! 

Despite this, I really enjoy using this lib! Thanks guys:)

**Comment by Kikketer** [comment]
Could you make an example of this type of thing in your documentation (readme.md).  I found it incredibly useful and I think others would like to see this right out of the gate.

**Comment by eleith** [comment]
great suggestion. done.

**Comment by RevealedFrom** [comment]
@legaultpierre , the `Content-Type` is still multipart/mixed for the email (top level, not any of the attachments).  As a result, some mail clients such as Gmail will not show the image until the user indicates positive.

How do I make the `Content-Type` of the mail multipart/alternative?
