### ISSUE TITLE
tls.createSecurePair is deprecated

### ISSUE THREAD

**Issue by roguejack** [eleith/emailjs#161]
Hi.
Seems like tls.createSecurePair() used in smtp/smtp.js [is deprecated since 0.11.3](https://nodejs.org/api/tls.html#tls_tls_createsecurepair_context_isserver_requestcert_rejectunauthorized_options).

How about updating the code to use newer API? (Support for node 0.10 would have to be dropped though).

**Comment by eleith** [comment]
done. thanks for pointing it out.
