### ISSUE TITLE
`TypeError: Third argument should be boolean` at `_tls_wrap.js:303`

### ISSUE THREAD

**Issue by strugee** [eleith/emailjs#162]
I'm working on e14n/pump.io, and recently emailjs@1.0.6 got pulled in. This breaks our tests:

```
% vows --spec test/email-notification-test.js

  ♢ email notifications

  When we set up the app
    ✓ it works
  When we set up the app and we get a new client
    ✓ it works
createCredentials() is deprecated, use tls.createSecureContext instead
_tls_wrap.js:303
  this.ssl = tls_wrap.wrap(this._handle, context.context, options.isServer);
                      ^
TypeError: Third argument should be boolean
    at TypeError (native)
    at TLSSocket._init (_tls_wrap.js:303:23)
    at new TLSSocket (_tls_wrap.js:275:10)
    at response (/Users/alex/Development/pump.io/node_modules/emailjs/smtp/smtp.js:244:32)
    at caller (/Users/alex/Development/pump.io/node_modules/emailjs/smtp/smtp.js:48:14)
    at response (/Users/alex/Development/pump.io/node_modules/emailjs/smtp/smtp.js:201:11)
    at caller (/Users/alex/Development/pump.io/node_modules/emailjs/smtp/smtp.js:48:14)
    at Socket.response (/Users/alex/Development/pump.io/node_modules/emailjs/smtp/smtp.js:181:11)
    at Socket.g (events.js:199:16)
    at Socket.emit (events.js:110:17)
util.print: Use console.log instead

✗ Errored » callback not fired
      in When we set up the app and we get a new client and we register two users
      in email notifications
      in test/email-notification-test.js
util.puts: Use console.log instead
✗ Errored » 2 honored ∙ 1 errored ∙ 1 dropped
```

Running `npm install emailjs@1.0.5` fixes this issue. I cloned this repo and bisected, which revealed that commit 80cfe787955c2f15f1d6d2299d7388000f369ff5 is causing this problem.

From that commit, it looks like Node 4+ is now required. If that's really the case, then the current release on npm should've been published as 2.0.0 as changing the Node version requirements is a **breaking change**. I would strongly suggest you unpublish 1.0.6 from npm unless you can immediately publish a fixed 1.x version, to prevent people from installing this broken release.

**Comment by eleith** [comment]
my apologies for the gaffe.

i have published a 1.07 release that should support older versions of node but avoid the deprecated function calls for newer versions of node.

**Comment by strugee** [comment]
Thanks very much! :)

**Comment by strugee** [comment]
@eleith our 0.10 builds are fixed but our 0.12 builds are still showing the same error, any ideas?

**Comment by eleith** [comment]
are you seeing the same deprecation warnings?

**Comment by strugee** [comment]
Yes. I'd just look at [the Travis build][1] and scroll to the bottom of the log :)

 [1]: https://travis-ci.org/e14n/pump.io/jobs/159372612

**Comment by eleith** [comment]
i pushed out v1.0.8 tonight.

v12 supports TLSSocket but expects a value of isServer. later versions of node default this to false.

supplying it seems to provide backwards support.

**Comment by strugee** [comment]
Can confirm this fixes the problems. Thanks!
