### ISSUE TITLE
sometimes getting "authorization.failed" errors

### ISSUE THREAD

**Issue by tomgrossman** [eleith/emailjs#163]
Hi,

For the long term the package works just fine, almost no issues at all.
But every once in a while I'm getting the following error:

> Unhandled rejection Error: authorization.failed
>     at module.exports (/root/dashboard/src/node_modules/emailjs/smtp/error.js:3:13)
>     at failed (/root/dashboard/src/node_modules/emailjs/smtp/smtp.js:458:28)
>     at response (/root/dashboard/src/node_modules/emailjs/smtp/smtp.js:463:13)
>     at caller (/root/dashboard/src/node_modules/emailjs/smtp/smtp.js:48:14)
>     at response (/root/dashboard/src/node_modules/emailjs/smtp/smtp.js:207:11)
>     at caller (/root/dashboard/src/node_modules/emailjs/smtp/smtp.js:48:14)
>     at TLSSocket.response (/root/dashboard/src/node_modules/emailjs/smtp/smtp.js:181:11)
>     at TLSSocket.g (events.js:260:16)
>     at emitTwo (events.js:87:13)
>     at TLSSocket.emit (events.js:172:7)
>     at notify (/root/dashboard/src/node_modules/emailjs/smtp/response.js:19:14)
>     at TLSSocket.watch (/root/dashboard/src/node_modules/emailjs/smtp/response.js:44:7)
>     at emitOne (events.js:77:13)
>     at TLSSocket.emit (events.js:169:7)
>     at readableAddChunk (_stream_readable.js:153:18)
>     at TLSSocket.Readable.push (_stream_readable.js:111:10)
>     at TLSWrap.onread (net.js:536:20)

I'm using only one `server` object, so I know it is connected because it is sending the rest of the mails (sometimes at the same exact time as the failed mail).
So it looks like it is loosing the connection, user or password sometimes when trying to send mails.

Are you aware of this issue? 
Is there a way I can debug it (open some debug\trace options maybe) so I can catch the problem when it happens? It is rarely happening (once a day or two days) so I can't catch it manually on a breakpoint or something.

thanks!

**Comment by eleith** [comment]
you can turn on debug by setting this to true -> https://github.com/eleith/emailjs/blob/master/smtp/smtp.js#L25

this will log all smtp transactions. 

have you tried updating to master as well, just in case?

**Comment by tomgrossman** [comment]
I'm on the latest version of course.
I will turn on debug and wait for it to reproduce.
Any more suggestions for now?

**Comment by eleith** [comment]
that should be good enough.

i think it might be possible that you just occasionally lose access and this library should just re authenticate you. so it might not be a problem. one problem however is that we throw an error and maybe there is a better way to handle that if we expect this from time to time.

let's see what you find out first.

**Comment by tomgrossman** [comment]
It is a problem, when I got these errors the mails that activated them weren't sent at all, so I don't think it was re-authenticated and resent the mails.
Anyway, I will try to reproduce it with debug somehow...

**Comment by tomgrossman** [comment]
@eleith so I reproduced the issue with debug on. It looks like you show a general error regarding authorization instead of the returned error from the SMTP server.
The error should be: `454 4.7.0 Too many login attempts, please try again later. xxxxxxxxxxxxxxx.1 - gsmtp`

> Debugger listening on port 41861
Tue Sep 27 2016 15:40:52 GMT+0300 (IDT) Listening on port 1337
connecting: smtp-relay.gmail.com:465
connected: smtp-relay.gmail.com:465
220 smtp-relay.gmail.com ESMTP xxxxxxxxxxxxxxx.1 - gsmtp

> ehlo tom-intsights

> 250-smtp-relay.gmail.com at your service, [5.29.193.208]
250-SIZE 157286400
250-8BITMIME
250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8

> AUTH LOGIN

> 334 xxxxxxxxxxxx

> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

> 334 xxxxxxxxxxxx

> xxxxxxxxxxxxxxxxxxxxxx==

> 454 4.7.0 Too many login attempts, please try again later. xxxxxxxxxxxxxxx.1 - gsmtp

> smtp connection closed.
Unhandled rejection Error: authorization.failed
    at module.exports (/home/tom/IntSights/dashboard/src/node_modules/emailjs/smtp/error.js:3:13)
    at SMTP.login.failed (/home/tom/IntSights/dashboard/src/node_modules/emailjs/smtp/smtp.js:494:28)
    at SMTP.login.response (/home/tom/IntSights/dashboard/src/node_modules/emailjs/smtp/smtp.js:499:13)
    at caller (/home/tom/IntSights/dashboard/src/node_modules/emailjs/smtp/smtp.js:48:14)
    at SMTP.command.response (/home/tom/IntSights/dashboard/src/node_modules/emailjs/smtp/smtp.js:207:11)
    at caller (/home/tom/IntSights/dashboard/src/node_modules/emailjs/smtp/smtp.js:48:14)
    at TLSSocket.SMTP.send.response (/home/tom/IntSights/dashboard/src/node_modules/emailjs/smtp/smtp.js:181:11)
    at TLSSocket.g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at TLSSocket.emit (events.js:172:7)
    at notify (/home/tom/IntSights/dashboard/src/node_modules/emailjs/smtp/response.js:19:14)
    at TLSSocket.watch (/home/tom/IntSights/dashboard/src/node_modules/emailjs/smtp/response.js:44:7)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at TLSSocket.Readable.push (_stream_readable.js:111:10)
    at TLSWrap.onread (net.js:536:20)

**Comment by eleith** [comment]
i've updated master to preserve the message. can you try with the updated master to see if this is more useful now?

**Comment by eleith** [comment]
closing this issue since the conversation died. i'm hoping the updated message was useful.
