### ISSUE TITLE
Embedding Image Stored Online

### ISSUE THREAD

**Issue by franalt** [eleith/emailjs#164]
Hey everybody.

Maybe someone can help me with this. I'am trying to embed an image that is stored online.

So far I've tried:  {path:"image_url", type:"image/png", headers:{"Content-ID":"my-image"}}
And: {data:"image_base64", encoded:true, name:"logo.png",type:"image/png"}

With no luck. With the base64 method the image is attached but the attached image appears "empty".

Anyone knows how to do this?

Thanks!

**Comment by eleith** [comment]
i have examples on how to embed images into your email here: https://github.com/eleith/emailjs#example-usage---attaching-and-embedding-an-image

you can also find general attachment examples in the test here: https://github.com/eleith/emailjs/blob/master/test/message.js#L222
