### ISSUE TITLE
erro 8

### ISSUE THREAD

**Issue by wilywork** [eleith/emailjs#165]
Help me, i am problems in send Email, fail with message -> {"code":8}

**Comment by eleith** [comment]
can you provide more information about how you got into that state? otherwise, it will be difficult to help.

**Comment by wilywork** [comment]
`
            var server = email.server.connect({
                user: empresa.userSmtp,
                password: empresa.passwordSmtp,
                host: empresa.hostSmtp,
                port: empresa.portSmtp,
                ssl: empresa.sslSmtp,
                tls: empresa.tlsSmtp,
                domain: empresa.domainSmtp
            });

        if(server){
            server.send({
                from: 'Toth <test>',
                to: "hezodions@gmail.com ,",
                cc: '',
                subject: "assunto",
                attachment: [
                    {data:"<html><body>hi<body></html>", alternative:true}
                ]
            }, function (err, message) {
                if(err){
                    console.log(" erro: "+JSON.stringify(err));
                } else {
                    console.log("Email enviado com sucesso!");
                }
            });
        }else{
            console.log("Erro ao enviar Email: não foi possivel pegar dados do servidor SMTP da empresa "+cnpjEmpresa+"  ou cadastro está incompleto.");
        }
`

**Comment by eleith** [comment]
you shouldn't need both the SSL and TLS options. i recommend TLS if your server supports it.

i don't know what error 8 is, that is not an SMTP error code. internally, emailjs also doesn't have a code 8 error.  have you tried a simpler message (no attachment, all strings, single to header) to get it working?

might be your email server?

**Comment by eleith** [comment]
seems like the error is from outside the application. if you can reproduce, we can try and debug later.
