### ISSUE TITLE
TypeError: Cannot read property 'connect' of undefined

### ISSUE THREAD

**Issue by anthnyprschka** [eleith/emailjs#169]
So I tried both 1) installing emailjs via npm and requiring via 

`var email = require('emailjs');`

and 2) copying the emailjs folder in my current directory and requiring via

`var email = require('./emailjs/email.js');`

but it always throws me the error

`TypeError: Cannot read property 'connect' of undefined`

at this line:

`var server  = email.server.connect({`

Anybody know what's this all about?

**Comment by duythanh90** [comment]
try this:
var Client = require("emailjs/smtp/client");
....
....
                var server = Client.connect({
});

**Comment by eleith** [comment]
my guess is that npm installation failed. 

check in your node_modules folder to see if emailjs is there and then check to see that folder has the source code.
