### ISSUE TITLE
How to listen for errors on email.server.connect() ?

### ISSUE THREAD

**Issue by premitius** [eleith/emailjs#170]
I want to handle all errors from `email.server.connect()`. How do you listen for errors for that function and could you add it to the documentation?

Kind regards
premitius

**Comment by eleith** [comment]
good point.

calling connect does not make contact with the server, but merely configures the client for when you contact it with send requests. thus, the way you listen for connection errors is on callbacks when sending email. 

if there is a connection issue, you'll find out then.
