### ISSUE TITLE
Sending no-reply emails.

### ISSUE THREAD

**Issue by jansilva** [eleith/emailjs#171]
Hi my friends. How are you? I hope you are fine.

    So, anyone know how to sending no-reply email? I'm trying to send one with the following set up:

 mailServer.send({
        from: mailFrom,
        to:mailTo
        cc: '',
        'reply-to': <empty>,
        subject: subject,
        attachment: [
          { data: body, alternative:true, inline: true },
        ]
      }, (err, message) => {
   ....

It sends an email, but I'm able to answer in my mailbox.

Thanks in advance.

**Comment by eleith** [comment]
i believe the common practice is to create an email account like `no-reply@your-domain.com` set an auto-responder on that account saying no one checks that email, and then use it in the `from` field when sending out email.
