### ISSUE TITLE
How would I go about sending a stream (which is a PDF) that is roughly 3 times the buffersize?

### ISSUE THREAD

**Issue by nicolasiscoding** [eleith/emailjs#176]
I am attaching a receipt as a PDF which I am keeping as a stream

**Comment by nicolasiscoding** [comment]
Ok, my workaround for now is to convert the buffer to base64, and put the string in the data field and set encoding to true

**Comment by elidoran** [comment]
@nicolasiscoding would you mind showing me how you did that?

I'm trying to attach a PDF file and it doesn't work no matter what I do. I can send other kinds of files just fine.

I've tried:

1. providing it as a path with type 'application/pdf'
2. reading the file into a string and providing it as data (unencoded)
3. converting it to base64 and putting it in as data like you mentioned above with `encoded:true`

It always causes a "timedout" error. The file is about one megabyte in size (1.5 when encoded).

When I switch to attaching any of the other files they all go through fine as a path and type.

Thank you
