### ISSUE TITLE
Gmail setup

### ISSUE THREAD

**Issue by elliotrock** [eleith/emailjs#177]
I am curious how you setup gmail, you mention application specific password. I have created for front end apps but for a server specific implementation like Node, how would one do this?

**Comment by eleith** [comment]
there are a few steps

1) create an application specific password (https://support.google.com/accounts/answer/185833?hl=en)
2) use ssl
3) use port 465
4) use 'smtp.gmail.com'

after trying that, what problems do you run into?

**Comment by maotora** [comment]
Hi @eleith ,

I'm not sure but I can't seem to get App specific passwords anymore.
Not from Gmail or Outlook.
I used my normal password and it worked but I'm just not comfortable using that.
Thanks.

**Comment by czamp** [comment]
@maotora You may have solved this already, but have you enabled access for less secure apps in your Google Account Settings?

[From Gmail Support](https://support.google.com/accounts/answer/185833?hl=en):

> Note: You may not be able to create an App password for less secure apps. [Learn more about allowing less secure apps.](https://support.google.com/accounts/answer/6010255)

**Comment by maotora** [comment]
@czamp Yeah. 
Funny enough I just noticed that now after reading about it on the link you provided.
Then tested it with my Two-Factored email and it was present.

Thanks!
