### ISSUE TITLE
[Question] require("./path/to/emailjs/email");

### ISSUE THREAD

**Issue by LucasBrazi06** [eleith/emailjs#179]
Hi,

What does it mean 'path to emailjs'?

Usually, after doing an npm install, I do not specify any path to the lib!?

Or am I wrong...

Thanks,
Serge.

**Comment by eleith** [comment]
yeah, if you install with NPM, it just works.

the instructions were meant (a long time ago) for those that were installing it by hand.

perhaps i could just remove it =]

**Comment by LucasBrazi06** [comment]
Yep :-) !
