### ISSUE TITLE
Problem sending emails with links to Outlook

### ISSUE THREAD

**Issue by pabloDon** [eleith/emailjs#183]
Hi,

I am using version 1.0.8 in my NodeJS app with the following implementation:
`var message = {
                       text:    "Text",
                       from:    "foo@foo.com",
                       to:      user.email,
                       subject: "Subject",
                       attachment: [{data:emailTemplates.newWeekly(result.ops[0]._id), alternative:true}]
                    };

                    // send the message and get a callback with an error or details of the message that was sent 
                    server.send(message, function(err, message) { 
                        console.log(err || message); 
                    });`

Where `emailTemplates.newWeekly(result.ops[0]._id)`, I return a HTML string with some anchors. These anchors, when the message is opened in Outlook appears like: `[my_link]my_link` but if I open that email in Gmail or from a client, every link looks good.

**Comment by eleith** [comment]
i think this might be helpful: https://litmus.com/community/discussions/5007-outlook-com-url-showing-in-the-link-label
