### ISSUE TITLE
special chars in to/from

### ISSUE THREAD

**Issue by coolgk** [eleith/emailjs#184]
errors when an email address contains special chars
e.g. to: "Tue May 23 2017 17:15:40 GMT+0100 (GMT Daylight Time)" \<email@example.com\>

**Comment by eleith** [comment]
can you provide a snippet?

i tried this


```javascript
var server  = email.server.connect({
   user:      "user"
   password:  "pass",
   host:      "host",
   ssl:       true,
});

// send the message and get a callback with an error or details of the message that was sent
server.send({
   text:    "i hope this works", 
   from:    '"Tue May 23 2017 17:15:40 GMT+0100 (GMT Daylight Time)"<test@test.com>',    
   to:      "user@user.com",
   subject: "testing emailjs"
}, function(err, message) { console.log(err || message); });
```

and it doesn't result in any error

**Comment by coolgk** [comment]
Hi, 

Sorry, it works now... not sure what happened when I tested it last time... I had errors until I changed the name to a normal string...

However if I do:

from: '"Tue May 23 2017 17:15:40 GMT+0100 (GMT Daylight Time)" <email@example.com>'

In Gmail the name got converted to "Tue May 23 2017 17:15"@[HOSTNAME]:40 GMT+0100 (GMT Daylight Time)". \@hostname got added to the part of the name. I am not sure if this was caused by POSTFIX or this library. You might want to check?

Thanks for your reply.

**Comment by arpit1997** [comment]
shouldn't we close this as its already sorted out 
` ` `
can you provide a snippet?

i tried this

var server  = email.server.connect({
   user:      "user"
   password:  "pass",
   host:      "host",
   ssl:       true,
});

// send the message and get a callback with an error or details of the message that was sent
server.send({
   text:    "i hope this works", 
   from:    '"Tue May 23 2017 17:15:40 GMT+0100 (GMT Daylight Time)"<test@test.com>',    
   to:      "user@user.com",
   subject: "testing emailjs"
}, function(err, message) { console.log(err || message); });
` ` `
