### ISSUE TITLE
Null Address valid  only as source (0.3.16)

### ISSUE THREAD

**Issue by Chiiviito** [eleith/emailjs#190]
No me envia correos
http://prntscr.com/fk47u6

**Comment by eleith** [comment]
at first guess, this seems to be something particular with how you are contacting your SMTP server.

can you reproduce this error?

have you tried contacting a different smtp server to verify you are using emailjs correctly?

**Comment by Chiiviito** [comment]
Hola! El error se produce porque un destinatario esta vacio.

Ejemplo:
"Roberto Calani <>"  = Error
"Roberto Calani <robertocalani@outlook.com>" = Good!

Regards!

**Comment by eleith** [comment]
ah.thanks. that is helpful

**Comment by eleith** [comment]
gracias
