### ISSUE TITLE
mimelib@0.2.14: This module is deprecated

### ISSUE THREAD

**Issue by ghost** [eleith/emailjs#191]
> ~: npm install emailjs
>
> npm WARN deprecated mimelib@0.2.14: This module is deprecated
>
> + emailjs@1.0.10
>
> added 8 packages in 30.811s

Maybe switch to another module?

**Comment by eleith** [comment]
the recommendation by the mimelib author is to use https://github.com/broofa/node-mime

**Comment by eleith** [comment]
that won't work. i only need one function the `mimeEncodedWord` function. will either have to implement it internally or find another library like https://github.com/emailjs/emailjs-mime-codec

**Comment by eleith** [comment]
this has been replaced in master
