### ISSUE TITLE
How send attachment encode from mongo? (0.3.16)

### ISSUE THREAD

**Issue by Chiiviito** [eleith/emailjs#192]
How send attachment encode from mongo? (0.3.16)

Example:
![encode](https://user-images.githubusercontent.com/12447729/27796378-328f2658-5fe0-11e7-8326-b5f4d60e4bec.png)

**Comment by eleith** [comment]
emailjs supports many different ways of sending attachments.

https://github.com/eleith/emailjs#attachment

you can save your data as a file and just give emailjs a path, you can store all the data as a string and send it, you can pass in the data as a stream. the other params allow you to detail the name you want it to be attached as, the filetype, charset, etc etc.
