### ISSUE TITLE
email.server.connect authentication parameter is mis-documented

### ISSUE THREAD

**Issue by inimino** [eleith/emailjs#193]
From the README:

    authentication // array of preferred authentication methods (ex: email.authentication.PLAIN, email.authentication.XOAUTH2)

It would be better if this was documented with a comprehensive list of allowed entries, rather than a partial example.

Also, exporting symbols for this doesn't seem necessary at all since they are just strings, and email.authentication.PLAIN is no more readable and less memorable than "PLAIN".

Finally, they don't seem to be exported under "email.server" anymore, but rather "email.SMTP".

In any case, diving into this didn't fix my problem, which was on the server side, but in case anyone needs to use this API feature it could be documented better.

**Comment by eleith** [comment]
sure, i can update the documentation to do an exhaustive list of the currently handled smtp authentication mechanisms.

using a hashed array was less about readability / memorability and more about usability / explorability. by exporting `emailjs.SMTP.authentication` you can produce the exhaustive list. however, with that said, a user doesn't have to use this and they can just use the strings instead. i'll make sure the documentation makes this clear.

**Comment by eleith** [comment]
updated docs in master
