### ISSUE TITLE
tls.connect error

### ISSUE THREAD

**Issue by maddurivenkys** [eleith/emailjs#196]
Hi All,

I'm getting  below error while testing the emailjs. Please let me know, your suggestions. 

AppComponent.html:1 ERROR TypeError: net.Socket is not a constructor
    at SMTP.connect (smtp.js:159)
    at Client._connect (client.js:78)
    at Client._poll (client.js:28)
    at client.js:115
    at Message.valid (message.js:154)
    at Client.send (client.js:93)
    at 

Code
======
sendMail():void {
//declare var require: any;
var email 	= require('../../../../node_modules/emailjs/email');
var server 	= email.server.connect({
 user:	"maddurivenkys@gmail.com",
 password:"********",
 host:	"smtp.gmail.com",
 //tls: {ciphers: "SSLv3"}
 ssl:		true
});

var message	= {
 text:	'i hope this works, thx to email js',
 from:	'Venkatesh <maddurivenkys@gmail.com>',
 to:		'Venky <maddurivenkys@gmail.com>,',
 cc:		'Venkatesh <maddurivenkys@gmail.com>',
 subject:	'testing emailjs - Venkatesh',
 /*attachment:
 [
    {data:"<html>i <i>hope</i> this works!</html>", alternative:true},
    {path:"path/to/file.zip", type:"application/zip", name:"renamed.zip"}
 ]*/
};

// send the message and get a callback with an error or details of the message that was sent
server.send(message, function(err, message) { console.log(err || message); });
=====

Thanks,
Venkatesh.

**Comment by eleith** [comment]
i believe that you are running this in the browser.

emailjs will only work on in a server nodejs environment, browsers do not support connecting to sockets.
