### ISSUE TITLE
Silent failure on misspelled options

### ISSUE THREAD

**Issue by inimino** [eleith/emailjs#199]
I hesitate to admit how many hours this cost me...

How quickly can you spot the problem here?

    emailjs.server.connect(
      {"username":"<redacted>"
      ,"password":"<redacted>"
      ,"tls":true
      ,"host":"<redacted>"
      ,"port":587
      });

Finally after sifting through log files on my mail server I found that the SMTP authentication just isn't happening at all. The "username" option does not exist, it should be "user".

So, my strong suggestion would be to whitelist the options and throw an exception if there are any unrecognized properties on the options object.

Would be happy to submit a PR for this...

**Comment by eleith** [comment]
that is a great UX suggestion. pull requests are welcome.

**Comment by maotora** [comment]
I also never got any emails until I understood my mixed options.

Please, some error message will be helpful.

**Comment by zackschuster** [comment]
as of 2ce27a2b9b14afea8e5267c787432c3974213912 the constructor will error if it receives a `password` but no `user`. closing this as i think that resolves things, but feel free to re-open if you have any concerns :)
