### ISSUE TITLE
build an example using emailjs with amazon SES

### ISSUE THREAD

**Issue by eleith** [eleith/emailjs#20]
emaijs exposes the Message object allowing it to be used independently to generate MIME formatted messages/attachments.

it would be nice to have an example showcasing this feature and to see if message.js needs to be modified to make this process feasible.

**Comment by reilg** [comment]
Can emailjs be used with SES? Or do I want to download the AWS SDK for node?
I keep getting a **timeout .. code 4 .. smtp underfined** error.

**Comment by eleith** [comment]
i have gotten around to trying it.

**Comment by reilg** [comment]
I'm sorry. You _have_ gotten around to trying it? So what were your results? 

I was testing it for a bit earlier today and these settings worked for me:

````javascript
var server = email.server.connect({
   user:    "user",
   password: "password",
   host:    "email-smtp.us-east-1.amazonaws.com",
   port: 	587,
   tls: true
});
````
All other settings would either return a code 4 or the SMTP server will outright reject the email. 

Hope this helps someone out.

**Comment by eleith** [comment]
i edited my comment =]

appreciate the info.
