### ISSUE TITLE
bad response on command

### ISSUE THREAD

**Issue by lszjl** [eleith/emailjs#200]
when i send an email, i got error: bad response on command ".":.............,what is wrong? anyone can help me?

**Comment by danielstaleiny** [comment]
allow less secure apps if you use gmail. for example

**Comment by eleith** [comment]
sorry, based on your description, there isn't enough details.

could you provide more information such that the error can be reproduced?

**Comment by CherryDT** [comment]
I have this exact error since a few days when sending emails from Amazon SES.
