### ISSUE TITLE
Wrong "from" address

### ISSUE THREAD

**Issue by JoshuaKeyz** [eleith/emailjs#204]
When you send the mail, instead of it to appear on the mail of the recipients as the {'from': '**'} address, it appears as the address of the user used to register the server For example
`
var server = email.server.connect({
user: "registerer",
password: 'soso',
host: 'host-@-.com',
ssl: true
})
server.send({
text: '***',
from: 'intended_sender',
to: 'intended_receiver',
cc: '***',
subject: 'asdfasf'
}, function(callback);
`
Now instead of the message to send as from: 'intended_server', it sends as user: 'registerer'

**Comment by eleith** [comment]
i can not reproduce.

what is the format of `intended_sender` that you are using?

can you confirm from the source of the email (many email clients allow you to look at the 'original' or 'source' of the email) that the FROM address is wrong? (some email clients may render a different from based on your address book.

i used your snipped of code and was able to very that the from is not send as the registerer.
