### ISSUE TITLE
warning

### ISSUE THREAD

**Issue by awaisaltaf** [eleith/emailjs#206]
var email = require("emailjs/email");

causing a warning... and reload page and do nothing

WARNING in ./~/encoding/lib/iconv-loader.js
9:12-34 Critical dependency: the request of a dependency is an expression

**Comment by eleith** [comment]
are you running this locally on the server? make sure you install with `npm install emailjs` so all the dependencies get resolved.

if you are trying to install directly from github, you'll need to run `npm install` in the emailjs folder to pull in all the dependencies
