### ISSUE TITLE
How to send HTML email from a file?

### ISSUE THREAD

**Issue by eyho** [eleith/emailjs#207]
Sending email as HTML works fine as long as I code it right into the attachment: [ ] part, now my question is, is there any way to 'require' the HTML file itself? Just like importing an image, but a HTML file instead.

Thank you in advance.

**Comment by eleith** [comment]
yes

see: https://github.com/eleith/emailjs#attachment

you can use the `path` field to point it to where the html file is. just make sure to also pass in the `alternative` field as well.
