### ISSUE TITLE
Update moment.js dependency version.

### ISSUE THREAD

**Issue by bunnyvishal6** [eleith/emailjs#209]
NSP listed moment.js with versions previous to 2.19.3 as vulnerable to ReDoS. Please see these links for more info [NSP-advisories-532](https://nodesecurity.io/advisories/532). And issue in [moment js](https://github.com/moment/moment/issues/4163).

**Comment by sarus** [comment]
Saw a PR for this  https://github.com/eleith/emailjs/pull/208 which looks closed rather than merged.  Any reason for that?  Would love to get rid of the NSP warning.

**Comment by bunnyvishal6** [comment]
Some tests were failing. I think some breaking changes are there with new moment.js and don't know how to resolve those so. I closed it. Hope the author of this repo fix those.

**Comment by mwakerman** [comment]
I just had a look and don't think momentjs is causing those issues. The same tests were failing before and after the bump for me. Could @eleith  have a look and potentially re-open #208 ?

**Comment by eleith** [comment]
i have it working in master. will publish this weekend
