### ISSUE TITLE
uncaught reference error exports is not defined

### ISSUE THREAD

**Issue by remcenit** [eleith/emailjs#211]
Hi i am building an MVC/Angular 2 application. So I had to configure my system.config file in order for the application to find the library. The problem arises when I try to use `var email = require('emailjs');` it gives me the following error on runtime:
`Error: (SystemJS) exports is not defined
	ReferenceError: exports is not defined`
It would be a great help. Thank you very much!

**Comment by eleith** [comment]
emailjs will only run server side in a nodejs environment, not the browser.
