### ISSUE TITLE
export the error codes?

### ISSUE THREAD

**Issue by r3ticuli** [eleith/emailjs#213]
why don't you guys export the error codes? would be helpful, no?

**Comment by eleith** [comment]
the error codes are exported: https://github.com/eleith/emailjs/blob/master/smtp/error.js

debug can be turned on manually to view the responses on the console: https://github.com/eleith/emailjs/blob/master/smtp/smtp.js#L25

**Comment by eleith** [comment]
ah, i see what you mean by your fork: https://github.com/r3ticuli/emailjs/commit/3e71f6bd7bf3bd742d63df2f507ee1641cb9647b

**Comment by r3ticuli** [comment]
is there a reason this wasn't done?
and thanks for investigating further despite closing the issue 😄

**Comment by eleith** [comment]
no reason. happy to except a pull request from your fork if you'ld like.

i closed the issue at first, because i misinterpreted the request. thanks for understanding.

**Comment by r3ticuli** [comment]
https://github.com/eleith/emailjs/pull/221

here's the PR. Thanks.
