### ISSUE TITLE
Continue supporting Node 4

### ISSUE THREAD

**Issue by strugee** [eleith/emailjs#215]
Node 4 is still in maintenance for a couple more months. I run a downstream project that depends on this and we've committed to the same timelines as Node.js itself - would it be possible to keep Node 4 on the list of supported versions, at least until upstream drops it?

See https://github.com/nodejs/Release#release-schedule

**Comment by eleith** [comment]
are there updates to the previous emailjs versions that you need?

unfortunately, some libraries that i use in the tests require node 6+, so i would have to re-work the tests in order to verify if things pass in node 4 and node 5.

**Comment by strugee** [comment]
Ah, gotcha. I can definitely understand that and given that Node 4 is so close to EOL anyway it's probably not worth doing anything about. I'll add upgrading emailjs to our list of things to do when we drop Node 4.

Cheers!

**Comment by eleith** [comment]
the only difference between the latest release and the previous are an upgraded moment and some smtp libraries due to some libraries being deprecated.

so there shouldn't be any real impactful change. =]

**Comment by strugee** [comment]
Yep, I figured. Meant to close this myself in fact, not sure why I didn't.

Thanks again!
