### ISSUE TITLE
tls.connect is not a function

### ISSUE THREAD

**Issue by Eimisg** [eleith/emailjs#216]
when I put  email.server.connect({...}) into variable it shows error "tls.connect is not a function", but when I just console log it - no error.

`import {Component, OnInit} from '@angular/core';
declare var require: any;

@Component({
  selector: 'app-about',
  templateUrl: './about.component.html',
  styleUrls: ['./about.component.css']
})
export class AboutComponent implements OnInit {

  constructor() {
  }

  ngOnInit() {
}

  send() {
    const email = require('../../../../node_modules/emailjs/email');
    const server = email.server.connect({
      user: '*****',
      password: '???',
      host: 'smtp.****@gmail.com',
      ssl: true
    });
    server.send({
      text: 'i hope this works',
      from: '*****@gmail.com',
      to: '******@gmail.com',
      subject: 'testing emailjs'
    }, function (err, message) {
      console.log(err || message);
    });
  }
}
`

**Comment by eleith** [comment]
how did you install emailjs? did you use `npm install emailjs` ?

if so, you only need to `require('emailjs')` and not provide the exact path to it.

i'm able to run your example code and not get the error your are reporting...

**Comment by pStigio** [comment]
Hi eleith,
I have the same problem. I do everything what you mention but it still doesn't work. When I put tls into console.log() before the line which throws error it retun { }. Have you got any idea what am I doing wrong?

**Comment by eleith** [comment]
what node version are you using? i'm unable to replicate, so maybe with a better understanding of the environment that leads to this, we can find a way to resolve it.

**Comment by pStigio** [comment]
I was using 6.11, upgrade it to 8.10. I create project with angular/cli v 5.2.8. The strange thing is that when I type npm install in command promt it doesn't install emailjs in node_modules. I have "emailjs": "^2.0.0" in package.json of course. I must install it manualy. When I look at package-lock.json I seen emailjs version 2.0.0 installed which is different from https://github.com/eleith/emailjs/blob/master/package.json.

**Comment by eleith** [comment]
hmm. that is odd.

if you install it manually, please check to make sure all dependencies are installed. it sounds like there is a dependency which might be missing.

to install dependencies just `npm install` when inside the emailjs directory.

**Comment by pStigio** [comment]
I done what you suggested, after npm install inside emailjs directory I got an error: "Can't find Python executable "python", you can set the PYTHON env variable." I set it up with help https://stackoverflow.com/questions/15126050/running-python-on-windows-for-node-js-dependencies and still got "tls.connect is not a function".

**Comment by eleith** [comment]
ah.

hmm, i am unable to test with windows right now to help you debug further.

i did find this though: https://github.com/bnoordhuis/node-iconv/issues/174

seems like there are some issues with install iconv on windows 64. that is likely to be fixed soon.

you could follow that thread for when it is resolved. there is also a suggested fix in that thread, so you could patch it yourself and try it out if you didn't want to wait.

**Comment by wozniakbe** [comment]
I still get this error. If I try to set SSL to false, I get another error `Uncaught TypeError: net.Socket is not a constructor`

Any resolution for this?

**Comment by ishroid** [comment]
Exactly same issue ,I installed from npm and using  `const email = require('emailjs');`
:-( please help

**Comment by eleith** [comment]
in order to help debug the problem please report

1) what version of emailjs you are using
2) what operating system you are using (macOSX, linux, windows)
3) how you installed emailjs

if you are receiving an error other than "tls.connect is not a function" please open up a new bug, since this thread here is focused on that error and not others like "net.Socket is not a constructor"

**Comment by JulianeH** [comment]
I got the same error with emailjs ^2.0.0, installed via npm on macOS
ERROR TypeError: tls.connect is not a function

**Comment by eleith** [comment]
are you trying to load emailjs in a browser environment? `tls.connect` is not a function would most likely happen in two situations

1) you have a server environment that didn't load the TLS library (core to nodejs)
2) you are loading emailjs in a browser and normal nodejs libraries don't work in the library (ex: tls)

i will check this out on a mac later today to see if something in my dependencies changed recently causing it not to work on a typical nodejs environment there. thanks for the report @JulianeH

**Comment by hoverfrog** [comment]
I get this error when running
ERROR TypeError: tls.connect is not a function
    at SMTP.connect (smtp.js:188)

OSX, installed emailjs with _npm install emailjs_, ran _npm install_ from inside the emailjs directory

package.json  shows:
"dependencies": {
    "@angular/animations": "^6.0.3",
    "@angular/cdk": "^2.0.0-beta.12",
    "@angular/common": "^6.0.3",
    "@angular/compiler": "^6.0.3",
    "@angular/flex-layout": "^5.0.0-beta.14",
    "@angular/forms": "^6.0.3",
    "@angular/http": "^6.0.3",
    "@angular/material": "^2.0.0-beta.12",
    "@angular/platform-browser": "^6.0.3",
    "@angular/platform-browser-dynamic": "^6.0.3",
    "@angular/router": "^6.0.3",
    "@types/lodash": "^4.14.109",
    "core-js": "^2.5.7",
    "emailjs": "^2.1.0",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "jspdf": "^1.4.1",
    "lodash": "^4.17.10",
    "ngx-restangular": "^3.0.0",
    "rxjs": "^6.2.0",
    "rxjs-compat": "^6.2.0",
    "word-wrap": "^1.2.3",
    "zone.js": "^0.8.26"
  },

**Comment by eleith** [comment]
are you running this in the browser?

tls is a function provided by node on the server. if you are getting this error, then node's own core tls library is not being found.

this either means you are in the browser, your node environment is in a bad state, or something in your code has overwritten the tls library.

i just had someone land some changes to this library and they have verified all the tests pass on node in windows, mac and linux.

**Comment by hoverfrog** [comment]
ah, yes, I'm in the browser - client-side! 
So there's no way to run this from client-side?

**Comment by eleith** [comment]
nope!

you can run this library in a cloud function properly lambda function and then expose it as an API to your app though.
