### ISSUE TITLE
Optional arguments passed to the SMTP object do result in a throw if undefined is passed

### ISSUE THREAD

**Issue by SanderDeWaal1992** [eleith/emailjs#225]
When I omit for example the 'timeout' option, it works ok. If I set timeout to be undefined, it does throw:

```
// Does go well:
emailJs.server.connect({
	user: "username",
	password: "password",
	host: "127.0.0.1",
	port: 1234
});
// Does not go well:
// Will throw  `The "msecs" argument must be of type number. Received type undefined`
emailJs.server.connect({
	user: "username",
	password: "password",
	host: "127.0.0.1",
	port: 1234,
	timeout: undefined
});
```
This problem occurs since version 2.1.0. Version 2.0.0 did work as expected.

**Expected behavior** 

both of above code snippets should work the same way.

**Comment by zackschuster** [comment]
@SanderDeWaal1992 this is due to some faulty logic with [the Object.assign call in the SMTP constructor](https://github.com/eleith/emailjs/blob/master/smtp/smtp.js#L54). i've [put up a PR](https://github.com/eleith/emailjs/pull/226) to fix this.
