### ISSUE TITLE
empty base64 png images

### ISSUE THREAD

**Issue by code-by** [eleith/emailjs#227]
I have following code:
```
    const data = `
<html>
    <img src="cid:image-logo" width="100">
</html>
`;

    EmailService.sendMail({
      from: 'foo@gmail.com',
      to: 'bar@gmail.com',
      subject: 'test',
      attachment: [
        {
          data,
          alternative: true,
          related: [
            {
              // path: 'file.png', // for PNG
              path: 'file', // for BASE64
              encoded: true,
              type: 'image/png',
              name: 'logoImage.png',
              headers: { 'Content-ID': '<image-logo>' },
            },
          ],
        },
      ],
    });
  });
```

When I use standart PNG file I receive email with image, when I use base64 image/png - empty image.

**Comment by eleith** [comment]
if you have the base64 of your image, you can avoid using attachments entirely and just write your HTML like this:

```
<html>
    <img src="data:image/jpeg;base64,---YOUR-BASE-64-IMAGE-HERE---" width="100">
</html>
```
email clients control the behavior of matching up CID with the attachments, so there is likely not much this library can do.

you can read more about sendgrid's suggestions and FAQ about using images in emails

https://sendgrid.com/blog/embedding-images-emails-facts/
