### ISSUE TITLE
Possible to return the raw sent message?

### ISSUE THREAD

**Issue by tjrhodes** [eleith/emailjs#229]
Hi,

Firstly thanks for a great tool, I've been using it in a new project and it's nice to work with.

I get the returned message as an object, is it possible to get the raw mime message sent to the smtp server?

Thanks,

Tom.

**Comment by eleith** [comment]
there was an attempt at a PR that does this: https://github.com/eleith/emailjs/pull/219

essentially, you could add some hooks that one could listen to, so that you can get at the raw data.

**Comment by tjrhodes** [comment]
Hey,

Thanks, ok, I'll have a look at that PR in more detail.

**Comment by zackschuster** [comment]
as of c4ddedafe47a119deb2ed546c01afc8b4cfb805e the internal logic for creating the raw message object is exposed as a separate api; you should see this api available in the next major release.

i'm opposed to implementing data interceptors for this, as that introduces non-trivial performance implications. if you want to know what we're sending, it's far cheaper to just make a copy :)

closing for now, but feel free to re-open if you think there's a path forward.

**Comment by zackschuster** [comment]
@tjrhodes this is now live in `3.0.0` :)
