### ISSUE TITLE
[Feature Request] bcc only emails

### ISSUE THREAD

**Issue by marcelcremer** [eleith/emailjs#230]
Hello everyone,

the library has the "to" field as a required parameter. However, in many cases (especially since GPDR arrived), you don't want to have every recipient to know the other mail addresses, that also received the email. As for this it would be very usefuly, to allow bcc-only E-Mails.

Best Regards
Marcel

**Comment by eleith** [comment]
good point about thinking about GDPR!

for now, the workaround that i use is to set the from/to field as the same email address. 

otherwise, we'ld need to consider what the underlying SMTP protocol requires and make sure we stay compliant. given there is a workaround for now, we'll revisit this next time new features are introduced. (for now, this library is currently undergoing a number of infrastructure concerns to better stabilize/modernize)

**Comment by marcelcremer** [comment]
Hello Eleith,

thank you for your answer. What I did as a workaround was just sending "to"-Emails in a loop to every recipient whenever a list of bcc-only people should be adressed. So it's more of a convenience feature request, because it would be simpler to just provide a bcc only list. No hurry about that one :-)

BR
Marcel

**Comment by zackschuster** [comment]
@eleith based on my reading of the spec, the TO field isn't required: [`The destination fields of a message consist of three possible fields, each of the same form: The field name, which is either "To", "Cc", or "Bcc"...`](https://tools.ietf.org/html/rfc2822#section-3.6.3)

i think we could do this while still being spec-compliant?

**Comment by eleith** [comment]
agreed. i tried to find similar language in the SMTP rfc but couldn't. didn't think to look to IMF

**Comment by zackschuster** [comment]
the closest thing i can find in 2821 is this: `Any BCC fields SHOULD then be removed from the headers.  Once this process is completed, the remaining headers SHOULD be checked to verify that at least one To:, Cc:, or Bcc: header remains. If none do, then a bcc: header with no additional information SHOULD be inserted as specified in [32].` [32] happens to be the IMF

**Comment by zackschuster** [comment]
initial implementation in 10a850159cc94588793c617fb85a0e9f9cba9838.

**Comment by zackschuster** [comment]
@marcelcremer this is now live in `3.0.0`. enjoy! :)

**Comment by marcelcremer** [comment]
@zackschuster Awesome, gonna try it soon. Thank you so much 🥳
