### ISSUE TITLE
Outdated dependency

### ISSUE THREAD

**Issue by gunnik** [eleith/emailjs#232]
NPM outputs the following warning when installing:
`npm WARN deprecated text-encoding@0.6.4: no longer maintained`

The entire package is no longer maintained as of 19 days ago.

**Comment by zackschuster** [comment]
[I don't see any vulnerabilities on snyk](https://snyk.io/vuln/search?type=npm&q=text-encoding), so personally I wouldn't fret. The code's been around a long time & has yet to cause any problems.

At any rate it's a subdependency, so it'd require reworking the dep tree. A PR would be great :)

**Comment by technbuzz** [comment]
It is okay as long as it is prevented from dependencies like *event-stream*

**Comment by zackschuster** [comment]
i don't know if you're being sarcastic but &ndash; given what the person who owns the `text-encoding` repo chose to make publicly visible about themselves, i highly doubt they're the sort to hand the keys over to bitcoin hackers.

**Comment by kcivey** [comment]
It's been submitted as an issue on the dependency now: https://github.com/emailjs/emailjs-mime-codec/issues/28.

**Comment by zackschuster** [comment]
i don't think there's an issue here. feel free to re-open to file a PR.
