### ISSUE TITLE
Unable to Resolve 'crypto', 'fs', 'net', 'os', 'stream', 'tls'

### ISSUE THREAD

**Issue by abhisheklokare** [eleith/emailjs#236]
ERROR in ./src/assets/js/smtp/**smtp.js**
Module not found: Error: Can't resolve **'crypto'** in '<Local_Path>/smtp'
ERROR in ./src/assets/js/smtp/**message.js**
Module not found: Error: Can't resolve **'fs'** in '<Local_Path>/smtp'
ERROR in ./src/assets/js/smtp/**smtp.js**
Module not found: Error: Can't resolve **'net'** in '<Local_Path>/smtp'
ERROR in ./src/assets/js/smtp/**message.js**
Module not found: Error: Can't resolve **'os'** in '<Local_Path>/smtp'
ERROR in ./src/assets/js/smtp/**smtp.js**
Module not found: Error: Can't resolve **'os'** in '<Local_Path>/smtp'
ERROR in ./src/assets/js/smtp/**message.js**
Module not found: Error: Can't resolve **'stream'** in '<Local_Path>/smtp'
ERROR in ./src/assets/js/smtp/**smtp.js**
Module not found: Error: Can't resolve **'tls'** in '<Local_Path>/smtp'
i ｢wdm｣: Failed to compile.

ERROR in src/app/app.component.ts(70,17): error TS2304: Cannot find name 'require'.

**Comment by eleith** [comment]
my guess is either you are trying to run this in a browser environment or you have not installed the package through npm.

https://github.com/eleith/emailjs/issues/216#issuecomment-396337848

if you are running this server side, please install with `npm install emailjs`

**Comment by Tinoooo** [comment]
To add the dependency to the own package.json is in my opinion not the best solution. It should be in the package.json of emailjs.

**Comment by eleith** [comment]
`crypto`, `fs`, `net`, `os`, `stream`, `tls` are all node modules provided directly by nodejs itself. they do not need to be declared if you have installed and are running emailjs with node.
