### ISSUE TITLE
State in the docs that it's possible to communicate directly with local MTA

### ISSUE THREAD

**Issue by Buzut** [eleith/emailjs#237]
I wanted to send email through my server's Exim4. Hence, no `username` nor `password`, but still [SMTP](https://en.wikipedia.org/wiki/Message_transfer_agent).

[Nodemailer](https://nodemailer.com/transports/sendmail/) offers an option to pipe directly emails to `sendmail` or other MTA installed on the system. But again, as MTAs rely on SMTP protocol, their perfectly addressable through local SMTP. 

I discovered that it works fine if I leave `server {}` blank. But it should be stated in the docs that this is possible.

**Comment by eleith** [comment]
i wasn't aware it had this behavior and am a bit surprised.

i think if you passed in empty options to `connect` you would get this:

https://github.com/eleith/emailjs/blob/master/smtp/smtp.js#L356

so your default port would be `25` and default host would be `localhost`. 

i agree with you. it makes sense to document that these would be the defaults.

**Comment by zackschuster** [comment]
would the changes in adabafc86d59fb765e2798c130cd003c163777ae resolve this?

**Comment by Buzut** [comment]
Looks perfect to me, crystal clear!
