### ISSUE TITLE
Cannot send more than two mails on my PC

### ISSUE THREAD

**Issue by RevealedFrom** [eleith/emailjs#239]
I am sending a series of email from a Node Express app.

I use the `.send(msg, callback)` method with the callback parameter. I use the callback to send the next message. Shouldn't this ensure no additional messages are sent until `emailjs` has done with the current one?

This method works fine on my servers, AWS as well as GCE. However, when running during development on my PC (Windows VS Code), it sends the first two successfully and `.send` doesn't return for the third. The callback is never called.

What could possibly be wrong?  The same is happening on different PCs.

My code is something like:

    const email = require("emailjs/email");
    const mailServer = email.server.connect( ... config ...);

    function sendMail(from, to, body, subject, ..., cb, next) {
      const msg = { from: from, to: to, text: body, subject: subject, ... };
      mailServer.send(msg, (err) => { 
         cb(err, next); 
       })
    }

    const list = [ "x@abc.com", "y@def.com", "z@xyz.com" ];
    sendOne(null, 0);

    function sendOne(err, next) {
      if (next>=list.length) return;
      sendMail("...", list[next], ..., ..., ..., sendOne, next+1);
    }

**Comment by eleith** [comment]
you have a recursive function, so it can get a bit difficult to track down the errors. nothing obvious pops out to me. however i recommend a few different approaches to try and narrow down what might be happening

1) turn on debugging: https://github.com/eleith/emailjs/blob/master/smtp/client.js#L41 this will allow you to see some low level SMTP response logging so you can see what is happening and when

2) i suggest finding a way to rewrite your approach to avoid recursive calling of callbacks. perhaps one of these options will help you write in a more iterative style and it will help obviate anything that might be going wrong: https://medium.freecodecamp.org/how-to-make-a-promise-out-of-a-callback-function-in-javascript-d8ec35d1f981

**Comment by RevealedFrom** [comment]
Thanks.  Is `emailjs` designed to allow send and forget, ie can I don't wait for a mail to be "out of the system" and `.send` the next mail? I tried sending one after another (without setting the callback) on my PC and only the first mail was sent.

**Comment by eleith** [comment]
the client.js library does manage an internal queue for each `send` call that you make. i don't think there are any assumptions that `send` is only called when all callbacks have been finished. 

you will need to track all these outstanding calls though before you can exit the process however.

**Comment by zackschuster** [comment]
@RevealedFrom should we consider this issue resolved for you? are there any concerns we need to address?
