### ISSUE TITLE
Getting "Not a valid message format" for perfectly fine email

### ISSUE THREAD

**Issue by CkFreak** [eleith/emailjs#240]
I am using emailjs on two of my projects. On one it works like a charm and on the other a restart is required to get the same message sent. 

The code for both applications is about the same.

Here is my configuration: 
```javascript
const server = email.server.connect({
		user: "MY_USER_NAME",
		password: EMAIL_PASSWORD,
		host: EMAIL_HOST,
		port: 587,
		authentication: ["LOGIN", "PLAIN"],
		tls: true,
	});
```

These are the headers I am trying to send: 
```javascript
const mail = {
			from: 'SENDER_EMAIL',
			to: recipient,
                         text: `Some Content`,
			subject: "A Subject Line",
			attachment: [{
			        data: `<b>Some HTML Content</b>`,
				alternative: true
			}]
		};
```

Node Version ```v9.11.2```
Emailjs Version ```^2.2.0```
All my variables are ```!= undefinded || != null```. So this is not the issue. When ever I sent my request to dispatch this mail I get this error:
```javascript
message is not a valid Message instance
```
Apart from the fact, that it would be nice to know what exactly the code thinks it's missing, when I restart the server and do not change the request AT ALL, the mail sends. It also sends when you just wait about two minutes. 
This does not seem like desired behaviour as the SAME code works on my other project. 

I am willing to accept I am missing something here because it works on my other project. But at this point I have even rewritten the module. It just does not work. 

Please give me a tip here!
Thanks!

**Comment by eleith** [comment]
the error message is triggered when this function returns false 

https://github.com/eleith/emailjs/blob/a16e20059c26fad1d6a3d6488eaa7e6dc2fddbef/smtp/client.js#L190-L201

so given your code, my first hypothesis is that sometimes your `to` is an empty string, null or undefined.

**Comment by CkFreak** [comment]
I have found this line of code as well. I checked that my to is not undefined or null. There is always a value in the to property when the error occurs. It makes really no sense at all.

**Comment by CkFreak** [comment]
It seems to be just what you said (what else could it be). I apologize for this thread. 
I check that there is a recipient when the server gets a request so that it cannot be undefined. However there is something going on so that the recipient gets lost in the process of sending the mail. Definitely not an issue with this package though.
