### ISSUE TITLE
smtp.js:594 this.sock.write(data); Cannot read property 'write' of null at SMTP.message

### ISSUE THREAD

**Issue by amark** [eleith/emailjs#245]
Probably related to https://github.com/eleith/emailjs/issues/205 .

```
/app/node_modules/emailjs/smtp/smtp.js:594
this.sock.write(data);
TypeError: Cannot read property 'write' of null
at SMTP.message (/app/node_modules/emailjs/smtp/smtp.js:594:13)
```

Seems like writable socket `this.sock` is not being checked for ready state changes.

I might fork an ugly check to prevent crash, if others need/want or if this package still open to PRs/publishing. Tho, I was using this for sending debugging/crash reports (meta!) so I should probably switch to something less hacky than email.

**Comment by zackschuster** [comment]
the null reference exception was addressed as part of [this commit](https://github.com/eleith/emailjs/commit/3bb741b3a889f9b7a886c76918dada7be6c1d2cd#diff-4967ead72d4fb56544e962576a28ae65R587). the fix will go out in the next release.

thank you! :)

**Comment by zackschuster** [comment]
@amark this is now live in `3.0.0` :)
