### ISSUE TITLE
implement rfc2047 (mime word encoding)

### ISSUE THREAD

**Issue by zackschuster** [eleith/emailjs#247]
[emailjs-mime-codec](https://github.com/emailjs/emailjs-mime-codec) is no longer maintained. i'd like to replace it with a custom implementation like we did for momentjs. potentially this could shrink the bundle by quite a lot.

given how large a task this would be, i don't intend to start until after we ship v3.

[rfc](https://tools.ietf.org/html/rfc2047)

**Comment by zackschuster** [comment]
experimenting with inlining code from `emailjs-mime-codec` & replacing calls to `text-encoder` with the built-in `util` replacements 

before: 16,160 loc
after: 2,152 loc

promising!

**Comment by eleith** [comment]
nice!
