### ISSUE TITLE
simplify public api

### ISSUE THREAD

**Issue by zackschuster** [eleith/emailjs#249]
i came to the conclusion that the `export * as ... from '...'` business was helping no one, so i cut it out. relevant commits:

- smtp: drop namespaces from re-exports a2da2ddd37e905a64ffdcc1925c2a0fe02e210ad
- smtp: rename smtp.ts -> connection.ts 6d8ad4681872bdcef2bf39a1f59a84c7bd56ca0a
- email: add response module to public api 8a623452520d983581449f008bc2d28144fcb4fc
- chore: update readme d4ebf37c658343fb2d1ab2c0b66d00fdfd20b3b3

i don't figure this is a particularly controversial change. it does make me wonder if we should rename `Client` to `SMTPClient`, though, and i want to make sure `SMTPResponse` (should that be renamed as well? `SMTPResponseMonitor`?) belongs in the public api.

**Comment by eleith** [comment]
i like the proposal to change `Client` and `SMTPResponse`. it does feel cleaner and more intuitive.

**Comment by zackschuster** [comment]
done:

- smtp: rename Client -> SMTPClient 3355154e66d641e5c408e33f434782414fb0b5b8
- smtp: rename SMTPResponse -> SMTPResponseMonitor 53c7087555744a17aef9f6a9c3c1b45c2609d5fc
