### ISSUE TITLE
bundle updates & versioning

### ISSUE THREAD

**Issue by zackschuster** [eleith/emailjs#250]
i have clearance at work to start integrating the latest updates, so we'll have some insight into possible regressions soon. (hopefully none! 🤞) 

for me that means swapping out the rollup bundles. i intend to use a fresh build — as opposed to what's on master — but i'm unsure whether i should check it in. is it important to keep those tied to the latest package version? alternately, should we take a lax "Last Known Good" approach and allow frequent updates? in whichever case, what should the process look like?

i don't feel particularly strongly toward any option personally.

**Comment by eleith** [comment]
i would advocate for `rollup/` to contain the latest build that matches the version number in `package.json`. seems like the path of least "surprise".

**Comment by zackschuster** [comment]
that's fine with me. since you're the publisher, would you like to manage updating the bundles? i can add a `prepublishOnly` script to run the build for you.

**Comment by zackschuster** [comment]
in line with this policy, i re-added the old bundle in 37ace28235a4bf93f7e61b7ff90a598d8c1832bc. it's not referenced anywhere & the test suite no longer works with it, though.

**Comment by eleith** [comment]
by updating the bundles, do you mean executing `npm run build` and then publishing to npm registry? (i'm assuming after we bump it to version 3.0) ?

**Comment by zackschuster** [comment]
yes, as well as pushing to the repo.

**Comment by eleith** [comment]
@zackschuster PR is up. after you approve, i'll merge and then publish to npm
