### ISSUE TITLE
rename default branch

### ISSUE THREAD

**Issue by zackschuster** [eleith/emailjs#257]
tech has been moving away from "master/slave" terminology for a while & the BLM protests have only accelerated those efforts. i agree with the politics behind the shift & suggest we follow suit.

the change can be accomplished by first running the following commands:
```
git branch -m master $NEW_NAME
git push -u origin $NEW_NAME
``` 
then following the instructions in [this guide](https://help.github.com/en/github/administering-a-repository/setting-the-default-branch).

the `master` branch will still remain on github. it can be deleted from the web interface or by running the following command:
```
git push -d origin master
```

to inform people of this change, i suggest pinning this issue for easy reference when errors occur.

here is a shortlist of proposed names:
- `main`
- `primary`
- `default`

suggestions are of course welcomed :)

**Comment by eleith** [comment]
https://twitter.com/natfriedman/status/1271253144442253312

i assume github would confer with others (gitlab, jira, etc) in the industry and hopefully take lead in getting everyone to do something consistent.

i like `main`, but if github chooses `primary` then i would prefer consistency.

i propose waiting a few weeks to see if they take timely action and we can do this step once.

**Comment by zackschuster** [comment]
agreed, let's plan around whatever github's action will be. based on that twitter thread it looks like they're going with `main` as well :)

**Comment by zackschuster** [comment]
i've pinned this issue as a statement-of-intent to do this at some point.

**Comment by zackschuster** [comment]
[small update](https://twitter.com/billygriffin22/status/1272563491287654401): they're going to change the default for new branches & "share guidance" for existing repos. feels like they're going to punt to the user base instead of touching data themselves. still, i think we should wait a bit longer to at least see what the new default will be.

**Comment by eleith** [comment]
sounds good. we can update once it is rolled out and we will be consistent.

**Comment by zackschuster** [comment]
here's the [official guidance](https://github.com/github/renaming#later-this-year-seamless-move-for-existing-repositories-):

> By the end of the year, we'll make it seamless for existing repositories to rename their default branch. When you rename the branch, we’ll retarget your open PRs and draft releases, move your branch protection policies, and more - all automatically. We’re updating GitHub Pages to allow building from any branch. And, we’re also looking into redirecting users who git fetch or git clone the old branch name to the new branch name (with a warning and instructions to update their local clone), so it’s easy for your contributors to move. You’ll be able to do a rename from GitHub.com, GitHub Desktop, or the CLI.

**Comment by mikestopcontinues** [comment]
Hey, regardless of how popular this change seems right now, I think it's worth considering if this kind of taboo-creation really gets us to the post-racial society we're all interested in reaching. It seems likely it will only retard our ability to get there. Here's one of the most popular linguists alive, John McWhorter, who's both black and liberal, discussing why this sort of rename is actually [a bad idea](https://reason.com/2020/08/12/is-your-master-bedroom-racist/).

**Comment by zackschuster** [comment]
@mikestopcontinues i wouldn't say anyone's trying to "create" taboo so much as address an unfortunate parallel; if anything, i'd classify this as more of a collective act of virtue signaling. if that's all it takes to persuade someone to abandon racial equality, i rather assume they weren't very on-board with the idea in the first place. 

also, the person who picked the default branch name ["wished many times [he] would have named them "main" (and "upstream") instead"](https://twitter.com/xpasky/status/1271477451756056577), which i think on its own invalidates any sort of historical argument for keeping it.

**Comment by mikestopcontinues** [comment]
I think about it like this: If we want to achieve a post-racial society, we have to take steps to dismantle the taboos that keep us thinking about skin color as any more noticeable or important than hair color. Our culture already has a lot of trip-wires that, when tripped, draw people's attention to race. The last decade, for all its filter bubbles and click-baitification, has multiplied the number of trip-wires we've got so that in some quarters identity politics is all anyone can think about. I find this especially concerning, since it goes counter to every metric we have, all of which suggests we're very, very close to closing all the gaps with regards to equality. 

We should be actively dismantling the trip-wires we have, not creating new ones (e.g. master, slave, blacklist, whitelist, etc.). Babies are being born all the time perfectly equipped to have a happy life with one another, but try and list all the stigmas you'd have to teach them just to keep from being cancelled on twitter. In an ideal world, there wouldn't be anything on the list. It kills me people are so ready to add more.

All that said, I'm not here to keep you from doing what you want with the library. I just found it today, and my ability to use it won't be impacted by whatever choice you make. :)

**Comment by zackschuster** [comment]
@mikestopcontinues i appreciate your attempt to explain your point-of-view but i respectfully disagree & intend to move forward with changing the branch name. we can discuss this further out-of-band if you'd like.

**Comment by PatrykMilewski** [comment]
Guys, there are so much open source repositories, that needs help with maintaining. I believe renaming branches from master to main is not really the highest priority and it simply changes nothing. Do you think that naming of technology-related stuff with words, that have been racist in the past, makes them also racist? It's nonsense. 

Maybe we should also think of renaming the standard for master-slave in hard disks? The question is, will it really help to decrease the racism on the world?
![image](https://user-images.githubusercontent.com/21146316/99654262-58ca2c80-2a5a-11eb-925a-119326cbf0c1.png)

What it will change? There are so much problems on the world and for some reason we keep on thinking about changing stuff, that doesn't make any difference. Is it really offensive to call branches in repository (where both of them are just abstract things, to simplify some concepts) master? Does it relate somehow to Black people? I don't think so.

I believe that if somebody is trying to find racism everywhere, it should be also called racism. Maybe let us stop looking for problems where they are not.

Personally I recommend disabling this GitHub non-sense using settings:
![Screenshot 2020-11-19 at 11 37 22](https://user-images.githubusercontent.com/21146316/99655274-d04c8b80-2a5b-11eb-9043-868cee4589f0.jpg)

**Comment by eleith** [comment]
later this year, github will release a tool to update the naming of the default branch to match that of github's standard default, which will be "main".

we are tracking the release of that tool  with this ticket and by following this page: 

https://github.com/github/renaming#later-this-year-seamless-move-for-existing-repositories-

thanks for the variety of inputs on the subject matter. it was quite informative!

i'll now lock comments as the decision has been made, and no further comments are needed. 

as with all decisions, there are tradeoffs and in the scheme of things, the tradeoffs of this decision have far more advantages than disadvantages for the main developers of this project.

**Comment by zackschuster** [comment]
unpinning since the future move will be seamless for outside collaborators.

**Comment by zackschuster** [comment]
@eleith i believe github is "done" implementing branch renaming. i scare-quoted because [the renaming repo is updated with instructions](https://github.com/github/renaming#renaming-existing-branches) but it doesn't look like it's fully seamless & i don't expect future effort as i've already seen microsoft update its repositories. i think it's ok to move forward with renaming to `main`.
