### ISSUE TITLE
SMTPClient is not a constructor

### ISSUE THREAD

**Issue by furfio** [eleith/emailjs#258]
I just follow the example in both node console and React app
but they all failed , why ? help!!

**Comment by zackschuster** [comment]
did you install `emailjs` as a dependency first?

due to reliance on node.js builtins, this library cannot run in the browser.

**Comment by furfio** [comment]
> did you install `emailjs` as a dependency first?
> 
> due to reliance on node.js builtins, this library cannot run in the browser.

Yes, I hava run npm install emailjs and my editor could find it rightly. I use it in the browser, in my React app ,  it seems not to work, saying not a constructor.  I mean, if I cannot just use it in the browser, where should I use emailjs? What's the working environment of this library?   I hope you could help me with it, thks a lot.

**Comment by eleith** [comment]
this library will not work on the client (browser).

instead, you'll need to run it on the server. if you run server side code with nodejs (http, express, koa, etc etc) then you can integrate with this library.

if you don't have access to your server code or your server code is written in another language, you'll need to find an alternative way to send email, sorry!

**Comment by saha-kpghoshal** [comment]
`// import { SMTPClient } from 'emailjs';
const SMTPClient = require('emailjs');

const client = new SMTPClient({
	user: 'someuser',
	password: '',
	host: 'somehost',
	ssl: true,
});

// send the message and get a callback with an error or details of the message that was sent
client.send(
	{
		text: 'i hope this works',
		from: 'some-sender',
		to: 'to-mail-id',
		subject: 'testing emailjs',
	},
	(err, message) => {
		console.log(err || message);
	}
);
`
This does not work, getting the following stack trace:

`TypeError: SMTPClient is not a constructor
    at Object.<anonymous> (/home/info/email-test/index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
`

nodejs version - 12.18.0
os - ubuntu 18.04

**Comment by zackschuster** [comment]
closing as answered. if we can help you out in another way, please let us know :)
