### ISSUE TITLE
send an email with an embeded image, the email not display image in Huawei mobile's email client

### ISSUE THREAD

**Issue by Yonysun** [eleith/emailjs#263]
send an email with an embeded image, the email not display image in Huawei mobile's email client

**Comment by zackschuster** [comment]
can you share the (redacted if necessary) message you're trying to send, as well as a code snippet demonstrating how you're using the library?

it might also be useful to run the library with debug mode on (call `client.smtp.debug(1)` prior to sending the message) and seeing if there are any errors or abnormalities that pop out.

**Comment by Yonysun** [comment]
`const { SMTPClient, Message } = require('emailjs');

const client = new SMTPClient({
    user: 'user',
    password: 'mypassword',
    host: 'outlook.server.com',
    tls: {
        ciphers: 'SSLv3',
    },
});

const message = new Message({
    text: 'i hope this works',
    from: 'user <user@outlook.com>',
    to: 'user2 <user2@outlook.com>',
    subject: 'testing emailjs',
    attachment: [
        {
            data:
                '<html>i <i>hope</i> this works! here is an image: <img src="cid:my-image" width="100" height ="50"> </html>',
        },
        {
            path: './image-path/anyone-pic.png',
            type: 'image/png',
            headers: { 'Content-ID': '<my-image>' },
        },
    ],
});

// send the message and get a callback with an error or details of the message that was sent
client.send(message, (err, message) => {
    console.log(err || message);
});`

**Comment by Yonysun** [comment]
const { SMTPClient, Message } = require('emailjs');

const client = new SMTPClient({
    user: 'user',
    password: 'mypassword',
    host: 'outlook.server.com',
    tls: {
        ciphers: 'SSLv3',
    },
});

const message = new Message({
    text: 'i hope this works',
    from: 'user <user@outlook.com>',
    to: 'user2 <user2@outlook.com>',
    subject: 'testing emailjs',
    attachment: [
        {
            data: '<html>i <i>hope</i> this works! here is an image: <img src="cid:my-image" width="100" height ="50"> </html>',
            charset: 'GB2312',
            alternative: true,
        },
        {
            path: './image-path/anyone-pic.png',
            type: 'image/png',
            headers: { 'Content-ID': '<my-image>' },
        },
    ],
});

// send the message and get a callback with an error or details of the message that was sent
client.send(message, (err, message) => {
    console.log(err || message);
});

**Comment by Yonysun** [comment]
[2.txt](https://github.com/eleith/emailjs/files/4879183/2.txt)
this is my test scripts, thank you very much.

**Comment by Yonysun** [comment]
the email can be sent to target account, but the embeded image not display normally

**Comment by zackschuster** [comment]
unfortunately i'm not (currently) familiar with how `cid` images are supposed to be inlined.

@eleith would you be able to advise?

**Comment by eleith** [comment]
cid image support isn't guaranteed in all email clients (though in practice, i've seen support for it in many of them)

https://sendgrid.com/blog/embedding-images-emails-facts/

the thing to check is that emailjs is producing the intended source (my guess it is, since i used this when sending to gmail a few months ago).

rfc for CID is here: https://tools.ietf.org/html/rfc2392 

some clients do support it, but deviate from the spec a bit.

**Comment by zackschuster** [comment]
@Yonysun can you verify the library is sending the email correctly? are there any issues we need to address?

**Comment by Yonysun** [comment]
> @Yonysun can you verify the library is sending the email correctly? are there any issues we need to address?

yes, I'm sure, and my Huawei mobile phone received the email successfully.

BTW: Huawei mobilePhone's email client can show email image sent from outlook client

**Comment by eleith** [comment]
i don't have access to an outlook client to inspect how it embeds images. it would be helpful to compare emailjs output to that of outlook to see if the implementations differ and how.

**Comment by eleith** [comment]
not enough info to reproduce
