### ISSUE TITLE
adopting new typescript features

### ISSUE THREAD

**Issue by zackschuster** [eleith/emailjs#264]
ts 4.0 [is currently in beta](https://devblogs.microsoft.com/typescript/announcing-typescript-4-0-beta/); like usual, it adds backwards-incompatible features, like control-flow analysis for class types & optional `any` or `unknown` types for `catch`-clause bindings. (there are also some true-blue breaking changes, but those don't affect our codebase.)

to me this raises coordination concerns with projects relying on our typescript files; since we can't assume users are using (or willing to upgrade to) latest typescript, we should be careful about breaking their projects. i see a few options:

1) never update typescript unless doing so would fix a user's project
2) update typescript, but be EXTRA CAREFUL about avoiding breaking changes
3) `semver-major` whenever we adopt a backwards-incompatible typescript feature (`emailjs@23`, here we come!)
4) keep our current versioning, essentially forcing users to upgrade their typescript
5) stop shipping source files, switching to a `.d.ts` model (using something like [`api-extractor`](https://api-extractor.com)) — i'll be honest, i put this last because i like shipping source.

right now this isn't really a concern since we're in a good spot stability-wise, but at some point i'm sure we'll be adding features & changing API contracts (e.g. by trading the callback-based model for a `Promise`-based model). before that happens, i would like to gain some sort of consensus about the best path forward.

**Comment by eleith** [comment]
1. :cry:  that would be sad (assuming some healthy adoption of newer ts releases)
2. :pray: nice in theory. like will break things in practice (eventually).
3. :balance_scale:  feels like a balanced tradeoff (assuming we aware when a new ts feature is being used and we update version accordingly)
4. :broken_heart: users can pin older versions but only after they realize (after a breakage) they can no longer get newer updates
5. :-1: 

(3) feels good enough

**Comment by zackschuster** [comment]
i concur; let's go with 3. i'll pin & leave open for a week or so to give people a chance to reply.
