### ISSUE TITLE
[VueJS]: TextEncoder Error When import emailjs

### ISSUE THREAD

**Issue by Marimax01** [eleith/emailjs#266]
Hi, 

I would like to send email with my  VueJS app but just import the lib to be display me an error.

I install it with npm like this  `npm i emailjs` 
In my main.js, I have:
`import { SMTPClient } from 'emailjs'; `

in my Chrome console I have this error:

```
email.cjs?e0e1:261 Uncaught TypeError: util.TextEncoder is not a constructor
    at Object.eval (email.cjs?e0e1:261)
    at eval (email.cjs:2084)
    at Object../node_modules/emailjs/rollup/email.cjs (chunk-vendors.js:6924)
    at __webpack_require__ (app.js:854)
    at fn (app.js:151)
    at eval (main.js:21)
    at Module../src/main.js (app.js:1360)
    at __webpack_require__ (app.js:854)
    at fn (app.js:151)
    at Object.1 (app.js:1481)
```

I do something wrong ?

**Comment by zackschuster** [comment]
Hello 😄 Unfortunately, `emailjs` doesn't work in browsers due to a reliance on Node.js built-in functions. If you want to send emails, you'll need to set up a server for your Vue.js app to interact with.

**Comment by Marimax01** [comment]
ok thanks for your feedback. Will you add all framework unsupported in the readme please ?

**Comment by zackschuster** [comment]
the very first sentence of the readme states:

> send emails, html and attachments (files, streams and strings) from node.js to any smtp server

so that won't be necessary. in fact, you can use this library in conjunction with server-side vue.js :smile:
