### ISSUE TITLE
async await syntax doesn't work

### ISSUE THREAD

**Issue by websocket98765** [eleith/emailjs#267]
Just a heads up that this doesn't send email successfully when using async/await syntax. The code runs through as if it succeeded (doesn't throw an error), but the email is not sent and `result` logs as `undefined`.

```js
  try {
    const result = await client.send(message);
    console.log('Email sent successfully', result);
  } catch (err) {
    console.error(err);
  }
```

The callback style in the docs works, of course.
```js
  client.send(message, (err, message) => {
    if (err) {
      console.error(err);
    } else {
      console.log('Email sent successfully', message);
    }
  });
```

But it might be good to support both.

**Comment by zackschuster** [comment]
the current version of the library is (mostly) written in the old "errback" style, so for now the recommendation is to use `util.promisify` and/or custom `Promise` wrappers for `async`/`await` workflows.

i'm not opposed to switching to a `Promise`-based interface in a future release. definitely open to a PR for this.

**Comment by zackschuster** [comment]
code snippet for `util.promisify` with `async`/`await`:

```ts
const client = new SMTPClient({});
const sendAsync = promisify(client.send.bind(client));

try {
  // SMTPClient#send only returns an error; you cannot currently `await` a result
  await sendAsync(message);
} catch (err) {
  // handle err
}
```

**Comment by eleith** [comment]
thanks @zackschuster lgtm
