### ISSUE TITLE
ERROR in node_modules/emailjs/smtp/address.ts:43:17 - error TS1109: Expression expected.

### ISSUE THREAD

**Issue by adjiandov** [eleith/emailjs#268]
I downloaded and installed emailjs, followed the startup guide, but whenever I do ng serve I get the following error. And there are many more like these.
43      if ((operator?.length ?? 0) > 0 && character === operator) {
                      ~
node_modules/emailjs/smtp/address.ts:43:26 - error TS1109: Expression expected.

43      if ((operator?.length ?? 0) > 0 && character === operator) {
                               ~
node_modules/emailjs/smtp/address.ts:43:29 - error TS1005: ':' expected.

43      if ((operator?.length ?? 0) > 0 && character === operator) {
                                  ~
node_modules/emailjs/smtp/address.ts:47:24 - error TS1109: Expression expected.

47      } else if ((operator?.length ?? 0) === 0 && OPERATORS.has(character)) {
                             ~
node_modules/emailjs/smtp/address.ts:47:33 - error TS1109: Expression expected.

47      } else if ((operator?.length ?? 0) === 0 && OPERATORS.has(character)) {
                                      ~
node_modules/emailjs/smtp/address.ts:47:36 - error TS1005: ':' expected.

47      } else if ((operator?.length ?? 0) === 0 && OPERATORS.has(character)) {
                                         ~
node_modules/emailjs/smtp/message.ts:2:13 - error TS1005: '=' expected.

2 import type { PathLike } from 'fs';
              ~
node_modules/emailjs/smtp/message.ts:2:31 - error TS1005: ';' expected.

2 import type { PathLike } from 'fs';
                                ~~~~
node_modules/emailjs/smtp/message.ts:5:13 - error TS1005: '=' expected.

5 import type { Readable } from 'stream';
              ~
node_modules/emailjs/smtp/message.ts:5:31 - error TS1005: ';' expected.

5 import type { Readable } from 'stream';
                                ~~~~~~~~
node_modules/emailjs/smtp/message.ts:558:25 - error TS1109: Expression expected.

558                             ? attachment.data ?? ''
                                                   ~
node_modules/emailjs/smtp/message.ts:559:37 - error TS1109: Expression expected.

559                             : Buffer.from(attachment.data ?? '').toString('base64'),
                                                               ~
node_modules/emailjs/smtp/message.ts:559:41 - error TS1005: ':' expected.

559                             : Buffer.from(attachment.data ?? '').toString('base64'),

**Comment by zackschuster** [comment]
it looks like you're using an older version of typescript. you'll need to update to at least 3.8 to get support for `type`-only imports & nullish coalescing.
