### ISSUE TITLE
 Cannot read property 'send' of undefined

### ISSUE THREAD

**Issue by photocherkaoui** [eleith/emailjs#271]
Hi,
  I use create-react-app and I follow the basic tutorial on integrating EmailJs in my react app.
I get this error in this file:
Form.js

import React from 'react';

export default class Form extends React.Component {
  constructor(props) {
	super(props);
	this.state = { adress:'' ,who:'', name: 'Sufra ',phone:'' , email: 'azerrtrt@gmail.com' };
	this.handleChange = this.handleChange.bind(this);
	this.handleSubmit = this.handleSubmit.bind(this);
  }

  render() {
	return (
  	<form className="test-mailing">
    	<h1>Let's see if it works</h1>
    	<div>
      	<textarea
        	id="test-mailing"
        	name="test-mailing"
        	onChange={this.handleChange}
        	placeholder="name"
        	required
        	value={this.state.who}
        	style={{width: '100%', height: '150px'}}
      	/>
		  	<textarea
        	id="test-mailing"
        	name="test-mailing"
        	onChange={this.handleChange}
        	placeholder="adress"
        	required
        	value={this.state.adress}
        	style={{width: '100%', height: '150px'}}
      	/>
		  	<textarea
        	id="test-mailing"
        	name="test-mailing"
        	onChange={this.handleChange}
        	placeholder="phone"
        	required
        	value={this.state.phone}
        	style={{width: '100%', height: '150px'}}
      	/>
    	</div>
    	<input type="button" value="Submit" className="btn btn--submit" onClick={this.handleSubmit} />
  	</form>
	)
  }

  handleChange(event) {
    this.setState({feedback: event.target.value})
  }
  handleSubmit (event) {
	const templateId = 'Vente';

	this.sendFeedback(templateId, {Name: this.state.who, from_name: this.state.name,Adress:this.state.adress,Phone:this.state.phone, reply_to: this.state.email})
  }

  sendFeedback (templateId, variables) {
	window.emailjs.send(
  	'gmail', templateId,
  	variables
  	).then(res => {
    	console.log('Email successfully sent!')
  	})
  	// Handle errors here however you like, or use a React error boundary
  	.catch(err => console.error('Oh well, you failed. Here some thoughts on the error that occured:', err))
  }
}

**Comment by zackschuster** [comment]
Hello 😄 Unfortunately, `emailjs` doesn't work in browsers due to a reliance on Node.js built-in functions. If you want to send emails, you'll need to set up a server for your React app to interact with.
