### ISSUE TITLE
Module '"fs"' has no default export

### ISSUE THREAD

**Issue by aoi-umi** [eleith/emailjs#272]
just an error in typescript
```ts
import fs from 'fs';  =>  import * as fs from 'fs';
```

**Comment by zackschuster** [comment]
do you have [`esModuleInterop`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#support-for-import-d-from-cjs-from-commonjs-modules-with---esmoduleinterop) enabled? node.js itself supports default imports for built-in modules, so we're unlikely to move from that syntax.

**Comment by aoi-umi** [comment]
> do you have [`esModuleInterop`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#support-for-import-d-from-cjs-from-commonjs-modules-with---esmoduleinterop) enabled? node.js itself supports default imports for built-in modules, so we're unlikely to move from that syntax.

i try this, but there is other packge had use `import * as pkg from 'pkg';`
so it throw error too
anyway, thx

**Comment by zackschuster** [comment]
sorry to hear that ☹️ best of luck!

**Comment by aoi-umi** [comment]
`allowSyntheticDefaultImports`
it seem work

**Comment by zackschuster** [comment]
added a note for this in ccf17f97a1018440ea427a2e8ae5325f80b3670f. thanks for the heads-up 😄
