### ISSUE TITLE
Bad Request -> POST https://api.emailjs.com/api/v1.0/email/send-form || The user ID is required. ||

### ISSUE THREAD

**Issue by jamesta696** [eleith/emailjs#276]
Hi, followed the exact tutorial steps from the website and keep getting "The user ID is required. To find this ID, visit https://dashboard.emailjs.com/admin/integration" bad request 400 error when testing Email JS. Can someone tell me what's wrong? 

Thanks!
Please see screen shots:

![image](https://user-images.githubusercontent.com/14171094/98637378-33605480-22dd-11eb-850a-c004538e3aec.png)

![image](https://user-images.githubusercontent.com/14171094/98637276-16c41c80-22dd-11eb-8ee0-3a3f930a8e3d.png)

![image](https://user-images.githubusercontent.com/14171094/98636778-5b02ed00-22dc-11eb-8378-59cfec8d1c39.png)

![image](https://user-images.githubusercontent.com/14171094/98636989-ae753b00-22dc-11eb-8b74-141b527712a1.png)

![image](https://user-images.githubusercontent.com/14171094/98637059-cea4fa00-22dc-11eb-873a-ff05fa7fe0b7.png)

**Comment by zackschuster** [comment]
hi @jamesta696! i see you've closed this issue already, but just in case i wanted to make clear that `emailjs.com` is unaffiliated with this project. the correct repo to submit issues against appears to be [emailjs-com/emailjs-sdk](https://github.com/emailjs-com/emailjs-sdk).

hope you're able to find your solutions 😄
