### ISSUE TITLE
cannot read property 'target' of undefined

### ISSUE THREAD

**Issue by Reset65** [eleith/emailjs#278]
Hello folks,

I'm new to working with JavaScript / relearning it. I'm working with EmailJS and VeeValidate I keep getting an error cannot read property 'target' of undefined. This only happens when I put <ValidationProvider></ValidationObserver> around any one of my inputs, unfortunately I have not been able to figure out what the issue is and I have looked every where for an example but been coming up empty handed. Here is a link to the vue page that I'm working with https://gist.github.com/Reset65/53a403aec6b7c983ac5b70d8b67a17d9 if anyone could give me a little guidance on what I should be doing or looking for that would be awesome.

Thanks,

**Comment by zackschuster** [comment]
Hi @Reset65 :) Unfortunately, you can't run `emailjs` in the browser, as it lacks the necessary APIs for sending emails. You'll have to run it from a Node.js instance to get it to work.
