### ISSUE TITLE
Question about storing configuration in a JSON file

### ISSUE THREAD

**Issue by EliteAspect21** [eleith/emailjs#279]
Sorry, but I couldn't mind any Discord server or anything like that. Is there a way to store the SMTP info in a .json file? One that I can host on my website and the bot fetches it and reads the details?

**Comment by zackschuster** [comment]
@EliteAspect21 hi there! we don't have any sort of community forum set up, so coming to the repo issues is fine :)

configuration files aren't supported, but you can retrieve the json details with a simple `require`:

```js
const { SmtpClient } = require('emailjs');
const smtpClientConfig = require('path/to/json/config');
const client = new SmtpClient(smtpClientConfig);
// etc.
```

or, if you prefer `import` and have `--experimental-json-modules` enabled:
```
js
const { SmtpClient } = require('emailjs');
const smtpClientConfig = require('path/to/json/config');
const client = new SmtpClient(smtpClientConfig);
// etc.
```
