### ISSUE TITLE
Type 'number' is not assignable to type 'Timer | null'.  TS2322

### ISSUE THREAD

**Issue by vmntruong** [eleith/emailjs#280]
Hello guys, 
I am facing to this issue just after install the package to my project (`yarn add emailjs`), then after I imported it using
`import { SMTPClient } from "emailjs";`

Here below the entire issue displayed in the console screen:

> C:/Users/Nhon/workspace/lcdd/clientLcdd/node_modules/emailjs/smtp/client.ts
> TypeScript error in C:/Users/Nhon/workspace/lcdd/clientLcdd/node_modules/emailjs/smtp/client.ts(168,4):
> Type 'number' is not assignable to type 'Timer | null'.  TS2322
> 
>     166 | 		// otherwise close out SMTP connection if still open
>     167 | 		else if (this.smtp.state() == SMTPState.CONNECTED) {
>   > 168 | 			this.timer = setTimeout(() => this.smtp.quit(), 1000);
>      | 			     ^
>     169 | 		}
>     170 | 	}
>     171 | 

Do you have any idea on this issue ?
Thank you so much !

**Comment by zackschuster** [comment]
we're using the `@types/node` definition for `setTimeout`, which has a different return object in node than in a browser. you'll need to make sure that `@types/node` is installed & in scope - though if that's the case i'm not sure why you see that error and not also dozens of errors for the `net`/`tls`/`fs`/etc imports.
