### ISSUE TITLE
How do you import with `require` syntax?

### ISSUE THREAD

**Issue by pilotkid** [eleith/emailjs#283]

**Comment by zackschuster** [comment]
i don't understand the question. are you trying to use `require` inside a module that uses `import` syntax? if so, you should use `[module.createRequire](https://nodejs.org/dist/latest-v14.x/docs/api/module.html#module_module_createrequire_filename)`

**Comment by pilotkid** [comment]
Hello, I apologize for not being clear. 

The examples provided are shown using this import syntax 
```js
import { SMTPClient } from 'emailjs';
```

However, when using this import syntax node throws the error `SyntaxError: Cannot use import statement outside a module`

Therefore, I am asking how are you supposed to import this module using `require()` instead of `import`

**Comment by GamerGirlandCo** [comment]
i had this problem too actually. the solution is to do 
```js
const { SMTPClient, Message } = require('emailjs')
```

**Comment by zackschuster** [comment]
it sounds like you're trying to use a `.js` file as a module. you'll need to set `"type": "module"` in your `package.json` to do that.

otherwise you can do as @GamerGirlandCo suggested and use the `require` syntax 😄

**Comment by pilotkid** [comment]
> it sounds like you're trying to use a `.js` file as a module. you'll need to set `"type": "module"` in your `package.json` to do that.
> 
> otherwise you can do as @GamerGirlandCo suggested and use the `require` syntax 😄

Perfect! Thank you! I haven't seen this type of import before for node and was not sure about how to go about resolving this issue. Thank you so much
