### ISSUE TITLE
node 10 support & the future

### ISSUE THREAD

**Issue by zackschuster** [eleith/emailjs#292]
node 10 will become increasingly hard to support as time goes on. [`ava`](https://github.com/avajs/ava/releases/tag/v4.0.0-alpha.1) and [`eslint`](https://eslint.org/blog/2021/06/whats-coming-in-eslint-8.0.0) have both signaled they will drop support in their next major versions, and `ts-node`'s current major version has (apparently) irreconcilable incompatibilities in its ESM and CJS support.

all of this is motivated by a broad desire by the ecosystem to reach an ESM-only world, and indeed it seems we're on the cusp of entering it. while a laudable goal, it doesn't really make a difference to this library as none of its features are locked into a module format; in fact, this means that to enter the ESM-only world, we would need to strictly weaken `emailjs`'s reach _regardless of future developments in node itself_.

unfortunately, if we wish to keep up with ecosystem enhancements, it means cutting that rope. the choice essentially becomes: do we lock down our dev dependencies at the moment they become incompatible with node 10, effectively locking the library into a slow freeze; or do we keep the future open, at the cost of our entire CJS story?

**Comment by eleith** [comment]
we could cut a release in the future that is the last release with CJS support and keep the future open.

if we do that, when do you think we'll need to cut such a release? end of year?

**Comment by zackschuster** [comment]
all currently supported major versions of node.js have a stable, unflagged esm implementation. given that, we can cut the release anytime we want -- presumably right before updating to ava@4, eslint@8 and ts-node@10.

**Comment by zackschuster** [comment]
update: `ts-node@10` can now override `"type": "module"`, which allows us to test our dual-package setup without sacrificing `node@10`. this means that as of d7b9236ed06cc3a74c056807b9d00da9596041d3, `yarn test` _now runs natively as ESM_ on `node@>=12`, while `yarn test-cjs` will always compile & run as CJS. woohoo! 

unfortunately, the tradeoff was being forced to use `--ignore-engines` to install on `node@10`, since `ts-node@10` deprecated that version. for now it's fine since we're only using `ts-node`'s legacy CJS code, but it does officially put us on borrowed time w/r/t upgrading. still, i believe this is as a pretty substantial win. 🎉
