### ISSUE TITLE
Is it possible to change destination email

### ISSUE THREAD

**Issue by techinp** [eleith/emailjs#293]
I would like to do dynamic destination email on this field by depend on template parameter

![Screenshot 2564-06-30 at 15 29 08](https://user-images.githubusercontent.com/44148263/123928236-ed651780-d9b7-11eb-8b28-e7d7fc9de449.png)

Is it possible?

**Comment by zackschuster** [comment]
yes, but you would have to send the address over a network connection to a server running the library. `emailjs` cannot be used in the browser.

**Comment by techinp** [comment]
@zackschuster Thanks
