### ISSUE TITLE
Duplicate Emails being sent or showing up in Yahoo

### ISSUE THREAD

**Issue by DKBoston15** [eleith/emailjs#300]
Using EmailJS, I receiving 2 emails in Yahoo despite only sending one.

I figured it was my code causing this, so I logged into EmailJS and tried it with a test email and it did the same thing. As you can see in the screenshot, I am receiving two emails at the exact same time. The EmailJS history tab only shows one email. I only have one service setup.

Am I doing something wrong here?

![Screen Shot 2021-09-15 at 9 48 30 PM](https://user-images.githubusercontent.com/46634008/133541415-f2159926-a26c-4e9b-982f-45db911d2b8d.png)

**Comment by eleith** [comment]
this is not the source for emailjs.com, you might be looking for https://github.com/emailjs-com instead
