### ISSUE TITLE
investigate macos timeouts

### ISSUE THREAD

**Issue by eleith** [eleith/emailjs#303]
originally all osx tests were timeing out.

upon a re-run, only node 14 was timing out, but after three tries still times out.

see: https://github.com/eleith/emailjs/actions/runs/2000036858

**Comment by zackschuster** [comment]
we've had flaky timeouts in the past, but it's definitely gone up a notch recently. i think the timeouts themselves are because `mailparser` is so slow, but i don't know why they would've increased so noticeably.

**Comment by zackschuster** [comment]
moved to https://github.com/eleith/emailjs/discussions/311
