### ISSUE TITLE
Can't send svg and canvas

### ISSUE THREAD

**Issue by GifinoThoriq** [eleith/emailjs#304]
I tried to send svg or canvas, but it didn't show in the email.
here's my code:
```
const message = await client.sendAsync({
				text: `Halo ${guest.name}`,
				from: 'Gintano & Nesya',
				to: `${guest.email}`,
				subject: 'Wedding Invitation!',
				attachment: [
					{ data: '<html> <span>halo semuanya</span> <svg width="400" height="100"> <rect width="400" height="100" /></svg></html>', alternative: true }
				]
			});
```

does this library have a function to send svg or canvas element?

**Comment by Wavesolid** [comment]
was looking this feature aswell, But still didn't find a way to do it.

**Comment by zackschuster** [comment]
i have a few questions:

- is any html data making it (such as your `<span>halo semuanya</span>`)?
- if not, does removing the `svg` code fix it?
- is this behavior consistent across email hosting providers?

we shouldn't be modifying your data from our library, so my first assumption is that it's the email hosts stripping out the svg code. i would reserve an investigation until after we've confirmed or denied this hypothesis.

**Comment by eleith** [comment]
not enough information to reproduce
