### ISSUE TITLE
Emails is not sent if used Iphone

### ISSUE THREAD

**Issue by E-Naeim** [eleith/emailjs#326]
Hi,

I'm trying to send emails from react web application

If used from any device or any browser, emails are sent

If used from Iphone, even any browser, it doesn't work

Is there any solution?

**Comment by eleith** [comment]
this library is a server side only library and will not work in browsers or other similar environments.

if you do not have a backend where you can write APIs and integrate this library into, then you'll need to use third party services or another library.
