### ISSUE TITLE
error - ./node_modules/emailjs/email.js:1:0  Module not found: Can't resolve 'fs'

### ISSUE THREAD

**Issue by 2tech-development** [eleith/emailjs#327]
I'm trying to use email.js in my nextjs website and getting this error

error - ./node_modules/emailjs/email.js:1:0
Module not found: Can't resolve 'fs'

**Comment by eleith** [comment]
this library will not work in the browser as it is intended for server environments.

if you want to send emails on the server with nextjs, you may want develop email sending APIs that can respond to requests from the browser

https://nextjs.org/docs/api-routes/introduction
