### ISSUE TITLE
Please tell me how to embed images in email.js what is cid:unique identifier ??

### ISSUE THREAD

**Issue by Srinivasan-Akash** [eleith/emailjs#328]

**Comment by eleith** [comment]
copy our [readme's example](https://github.com/eleith/emailjs#example-usage---attaching-and-embedding-an-image) to see how it works

`cid` is a spec used by some email clients that this library supports, you can read more about it on this page: https://sendgrid.com/blog/embedding-images-emails-facts/

in summary, the identifier is used to match up the html image reference to the image attachment

**Comment by Srinivasan-Akash** [comment]
after cid can i paste a hosted umage url

**Comment by Srinivasan-Akash** [comment]
how to embed image in HTML to shoot an Gmail via email.js
