### ISSUE TITLE
Minor vulnerability: Password leaks in error when authorization/authentication fails

### ISSUE THREAD

**Issue by Tethik** [eleith/emailjs#339]
When authentication towards the SMTP server fails emailjs returns an error that leaks the password used. If not specifically handled, this is could leak into logs / error tracking systems. 

Example message when printed (`cGFzc3dvcmQ=` is "password" as base64):
```
Error: authorization.failed (bad response on command 'cGFzc3dvcmQ=': 5.7.8 Error: authentication failed: authentication failure)
```
I noticed this as we were moving to a different SMTP provider internally. My service account did not have the correct authorization to access the new system, but still had a valid password. So while unlikely, it happens that valid credentials will leak.

**Comment by eleith** [comment]
thank you for the report. i'll investigate shortly.

**Comment by eleith** [comment]
`authorization.failed` error messages will now redact the password with `REDACTED`

**Comment by Tethik** [comment]
Thanks for the quick fix 🥇 

Maybe it's worth considering creating a security advisory? It will help inform organizations to patch this.

I may have another vulnerability as well from the same project that relates to this lib, need to dig a bit through our Jira though, will keep in touch.
