### ISSUE TITLE
Typescript error

### ISSUE THREAD

**Issue by ShreshthTiwari** [eleith/emailjs#340]
```
./node_modules/emailjs/smtp/client.ts:165:17
Type error: No overload matches this call.
  Overload 1 of 2, '(timeoutId: string | number | Timeout | undefined): void', gave the following error.
    Argument of type 'Timer' is not assignable to parameter of type 'string | number | Timeout | undefined'.
      Property '[Symbol.dispose]' is missing in type 'Timer' but required in type 'Timeout'.
  Overload 2 of 2, '(id: number | undefined): void', gave the following error.
    Argument of type 'Timer' is not assignable to parameter of type 'number'.

  163 |         protected _poll() {
  164 |                 if (this.timer != null) {
> 165 |                         clearTimeout(this.timer);
      |                                      ^
  166 |                 }
  167 | 
  168 |                 if (this.queue.length) {
  ```
node verseion- 18.17.0
npm version- 9.6.7
NextSJ App Version- 13.4.16

I am using the same package version in another nextjs app and it is working don't know why it is throwing this weird error only in this one.

**Comment by eleith** [comment]
i'm unable to replicate. 

are you buy chance trying to include this library in a page that is being compiled for the browser?

when using this library for server side logic (in a nextjs app) this doesn't happen for me.

you'll need to post more context about what is trigger this check for types and it might possibly be with something outside of control of this library...

**Comment by ShreshthTiwari** [comment]
This is my server side module, i am not even using it yet.
```
import { SMTPClient } from "emailjs";

const smtp = require("@/config/smtp.json");

interface Result {
  success: boolean;
  msg: string;
}

const client = new SMTPClient({
  user: smtp.username,
  password: smtp.password,
  host: smtp.host,
  ssl: true,
});

const sendMail = async (
  username: string,
  email: string,
  subject: string,
  htmlData: string
): Promise<Result> => {
  const result: Result = {
    success: false,
    msg: "",
  };

  if(!(username && email && subject && htmlData)){
    result.msg = "Values not provided.";

    return result;
  }

  try {
    const response = await client.sendAsync({
      text: "",
      from: `${smtp.name}<${smtp.address}>`,
      to: `${username}<${email}>`,
      subject: subject,
      attachment: [{ data: htmlData, alternative: true }],
    });

    if(response?.header?.["message-id"]){
      result.success = true;
      result.msg = "Email sent successfully.";
    } else {
      result.msg = "Error sending email.";
    }
  } catch (error) {
    console.log(error);

    if (typeof error === "string") {
      result.msg = error;
    } else if (typeof error === "object") {
      result.msg = JSON.stringify(error);
    }
  } finally {
    return result;
  }
};

export default sendMail;
```

**Comment by eleith** [comment]
the snippet does not show any type errors for me with typescript 4.8.4 and node v18.17.0

**Comment by eleith** [comment]
fwiw, we get the timer type directly from node here

https://github.com/eleith/emailjs/blob/3a4ba01e01047b9aa345f291049db97b6f3e3971/smtp/client.ts#L33

**Comment by Janl1** [comment]
I had the same exception. Resolving a missmatch with the version of `@types/node`  and `node` solved it for me.

**Comment by eleith** [comment]
ah. that makes sense, given the type error is about `NodeJS.Timer`, thanks for chiming in

**Comment by ShreshthTiwari** [comment]
so how to fix it?

**Comment by eleith** [comment]
the issue you are is that the typescript compiler you are using is finding an error with the types provided by your environment. we can not resolve that internally in this library. 

in my test, i have this library full types working in a quick test i put together with the following:

1. node 18.17.0
2. @types/node ^18.7.15
3. typescript ^4.8.2

**Comment by eleith** [comment]
node 20 does have a type change for `setTimeout` as detailed in #341 (this issue claimed it was node 18, but if mixed with types from node 20, it could be the root issue here)

this has been resolved now on latest
