### ISSUE TITLE
using emailjs with outlook smtp

### ISSUE THREAD

**Issue by manishkumarshr** [eleith/emailjs#44]
Hi,

I was trying to use emailjs with outlook smtp but unable to use. I am writing my options object something like this:

var server  = email.server.connect({
        user:    "my-use-mail-id",
        password:"my-passwrod",
        host:    "smtp.outlook.com",
        port:    xyz,
        ssl:     true
    });

when I do the same with gmail smtp, looks working great!! please give me a working example with outlook SMTP .

Thanks
-Manish

**Comment by manpreetgill** [comment]
Same problem face 
I get code 5 error for connecting to gmail (se below) and timeout as above when connecting to an in-house smtp:

emailjs.server.connect({
host: "smtp.gmail.com",
user: user, 
password: password,

ssl: true
});
Where user and password are my gmail account info...

Result:
{ [Error: connection encountered an error]
code: 5,
previous:
{ [Error: connect ECONNREFUSED]
code: 'ECONNREFUSED',
errno: 'ECONNREFUSED',
syscall: 'connect' },
smtp: undefined }

**Comment by manpreetgill** [comment]
solve that problem by stackoverflow
var email = require('emailjs');

var server = email.server.connect({
  user: 'nodejsiscool@gmail.com',
  password: 'stackoverflow',
  host: 'smtp.gmail.com',
  ssl: true
});

server.send({
  text: 'Hey howdy',
  from: 'NodeJS',
  to: 'Wilson <wilson.balderrama@gmail.com>',
  cc: '',
  subject: 'Greetings'
}, function (err, message) {
  console.log(err || message);
});
link://http://stackoverflow.com/questions/30598980/emailjs-not-working-node-js?answertab=active#tab-top

**Comment by junerockwell** [comment]
Just a thought/suggestion; Have you all thought that maybe this error (listed below) is caused by a firewall from your end? If so, then this firewall is probably blocking the stmp.

{ [Error: connection encountered an error]
code: 5,
previous:
{ [Error: connect ECONNREFUSED]
code: 'ECONNREFUSED',
errno: 'ECONNREFUSED',
syscall: 'connect' },
smtp: undefined }

It's something worth considering if you haven't.

**Comment by manpreetgill** [comment]
var https = require('https');
 https.globalAgent.options.secureProtocol = 'SSLv3_method';
var email = require('emailjs');
 var server  = email.server.connect({
                 user:    "name@yahoo.com", 
                 password:"node@2015", 
                 host: "smtp.mail.yahoo.com", 
                 ssl:     true
              });
  module.exports=server;
 I am try to  send emial by yahoo but cannot send email.
but this code is work in gamil.

**Comment by thEpisode** [comment]
WTF, header title is on OUTLOOK! not Gmail, not Yahoo. Thanks for solution @eleith

**Comment by yupswing** [comment]
I found this thread closed but actually I think the solution was not here yet.

the configuration, for any outlook server, asks for TLS using SSL version 3 
```
{
      "user":"xxxxx",
      "password":"xxxxx",
      "host":"xxxx.xxxx.xxx",
      "tls": {"ciphers": "SSLv3"}
}
```

Thanks to https://managuajs.wordpress.com/2015/07/07/enviar-email-con-outlookhotmail-usando-emailjs/ and https://stackoverflow.com/questions/11091974/ssl-error-in-nodejs/12683325#comment25535766_12683325

**Comment by qinfeng** [comment]
@ Hope my solution might be helpful.

In my case, I am using office365, I need to disable SSL and enable TLS as below to address **`SSL23_GET_SERVER_HELLO:unknown proto`** error:
``` 
port: 587,
ssl: false,
tls: true
```

**Comment by saravjotsingh** [comment]
```
code: 5,
  smtp: undefined,
  previous:
   { Error: connect ECONNREFUSED 74.125.200.108:465
       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
     errno: 'ECONNREFUSED',
     code: 'ECONNREFUSED',
     syscall: 'connect',
     address: '74.125.200.108',
     port: 465 } }
```

I am getting above error when i tried to connect with emailjs
It is working fine in localhost but its not working on server and it gives the above error.
plzz help.

 ```
var server  = email.server.connect({
   user:    "xyz@gmail.com", 
   password:************, 
   host:    "smtp.gmail.com",
   ssl:     true
});
```

**Comment by eleith** [comment]
try reading this thread: https://github.com/eleith/emailjs/issues/104

many users need to turn on application specific password as their default username/password won't work
