### ISSUE TITLE
does not send messages with error "Error: connection has ended"

### ISSUE THREAD

**Issue by himera444** [eleith/emailjs#58]
Hi!
Sometimes does not send messages with error:
{ [Error: connection has ended] code: 9, smtp: undefined }
Sometimes the messages are sent correctly with the same settings. How can I avoid this error?

**Comment by RevealedFrom** [comment]
Suddenly I am getting this same error as follows:

     Error: connection has ended
       at module.exports (/usr/lib/node_modules/emailjs/smtp/error.js:2:13)
       at TLSSocket.end (/usr/lib/node_modules/emailjs/smtp/response.js:55:29)
       at emitNone (events.js:111:20)
       at TLSSocket.emit (events.js:208:7)
       at endReadableNT (_stream_readable.js:1055:12)
       at _combinedTickCallback (internal/process/next_tick.js:138:11)
       at process._tickDomainCallback (internal/process/next_tick.js:218:9) code: 9, smtp: undefined

**Comment by eleith** [comment]
did you not get them in a previous version and are not seeing this?

you can turn on the debug flag to get more information on the console to see what exact SMTP communications are happening that lead to this, that could help dig deeper into how to avoid this.

**Comment by RevealedFrom** [comment]
Thanks for reply so quickly. Didn't get any errors before as the app was running trouble-free for a year. I suspect something on the SMTP server changed, but the error message was too cryptic.  Manual telnet test was ok from the same machine.

I couldn't find a debug option on your Readme.md. Could you share how.  Thanks again.

**Comment by eleith** [comment]
https://github.com/eleith/emailjs/blob/master/smtp/smtp.js

set `DEBUG` to 1 and save your console output.

**Comment by RevealedFrom** [comment]
Fixed my problem. It was the mail server.  DEBUG=1 let me see the detailed error reasons.

**Comment by gloompi** [comment]
for those who are interested, SMTPClient instance has an smtp field with debug method

`client.smtp.debug(1)`
