### ISSUE TITLE
Question: ssl connection - Error: SELF_SIGNED_CERT_IN_CHAIN

### ISSUE THREAD

**Issue by djesse** [eleith/emailjs#88]
Hi,

I am running an app with Node.js 0.8.8 and emailjs 0.3.4 which has no problems connecting to my smtp-server via SSL.

I updated Node to 0.10.21 and emailjs to 0.3.6 and and now I can't connect to my smtp server anymore. Connection fails with error: SELF_SIGNED_CERT_IN_CHAIN.

The mail server indeed has a renewed self-signed certificate but how can I solve this problem?

**Comment by Than890** [comment]
how can solve this error
